// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Market_Ping_FullMethodName                                       = "/market.Market/Ping"
	Market_FindMaxSupplyPairInfoByTokenAddrAndChainID_FullMethodName = "/market.Market/FindMaxSupplyPairInfoByTokenAddrAndChainID"
	Market_FindNearTokenPrice_FullMethodName                         = "/market.Market/FindNearTokenPrice"
	Market_FindNearBaseTokenPrice_FullMethodName                     = "/market.Market/FindNearBaseTokenPrice"
	Market_FindTokenInfo_FullMethodName                              = "/market.Market/FindTokenInfo"
	Market_FindPairInfoByPairAddress_FullMethodName                  = "/market.Market/FindPairInfoByPairAddress"
)

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	FindMaxSupplyPairInfoByTokenAddrAndChainID(ctx context.Context, in *PairInfoRequest, opts ...grpc.CallOption) (*PairInfo, error)
	FindNearTokenPrice(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponse, error)
	FindNearBaseTokenPrice(ctx context.Context, in *BaseTokenPriceRequest, opts ...grpc.CallOption) (*BaseTokenPriceResponse, error)
	FindTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	FindPairInfoByPairAddress(ctx context.Context, in *PairInfoReq, opts ...grpc.CallOption) (*PairInfo, error)
}

type marketClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketClient(cc grpc.ClientConnInterface) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Market_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) FindMaxSupplyPairInfoByTokenAddrAndChainID(ctx context.Context, in *PairInfoRequest, opts ...grpc.CallOption) (*PairInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairInfo)
	err := c.cc.Invoke(ctx, Market_FindMaxSupplyPairInfoByTokenAddrAndChainID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) FindNearTokenPrice(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenPriceResponse)
	err := c.cc.Invoke(ctx, Market_FindNearTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) FindNearBaseTokenPrice(ctx context.Context, in *BaseTokenPriceRequest, opts ...grpc.CallOption) (*BaseTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseTokenPriceResponse)
	err := c.cc.Invoke(ctx, Market_FindNearBaseTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) FindTokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, Market_FindTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) FindPairInfoByPairAddress(ctx context.Context, in *PairInfoReq, opts ...grpc.CallOption) (*PairInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairInfo)
	err := c.cc.Invoke(ctx, Market_FindPairInfoByPairAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
// All implementations must embed UnimplementedMarketServer
// for forward compatibility.
type MarketServer interface {
	Ping(context.Context, *Request) (*Response, error)
	FindMaxSupplyPairInfoByTokenAddrAndChainID(context.Context, *PairInfoRequest) (*PairInfo, error)
	FindNearTokenPrice(context.Context, *TokenPriceRequest) (*TokenPriceResponse, error)
	FindNearBaseTokenPrice(context.Context, *BaseTokenPriceRequest) (*BaseTokenPriceResponse, error)
	FindTokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error)
	FindPairInfoByPairAddress(context.Context, *PairInfoReq) (*PairInfo, error)
	mustEmbedUnimplementedMarketServer()
}

// UnimplementedMarketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServer struct{}

func (UnimplementedMarketServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMarketServer) FindMaxSupplyPairInfoByTokenAddrAndChainID(context.Context, *PairInfoRequest) (*PairInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMaxSupplyPairInfoByTokenAddrAndChainID not implemented")
}
func (UnimplementedMarketServer) FindNearTokenPrice(context.Context, *TokenPriceRequest) (*TokenPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNearTokenPrice not implemented")
}
func (UnimplementedMarketServer) FindNearBaseTokenPrice(context.Context, *BaseTokenPriceRequest) (*BaseTokenPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNearBaseTokenPrice not implemented")
}
func (UnimplementedMarketServer) FindTokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindTokenInfo not implemented")
}
func (UnimplementedMarketServer) FindPairInfoByPairAddress(context.Context, *PairInfoReq) (*PairInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPairInfoByPairAddress not implemented")
}
func (UnimplementedMarketServer) mustEmbedUnimplementedMarketServer() {}
func (UnimplementedMarketServer) testEmbeddedByValue()                {}

// UnsafeMarketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServer will
// result in compilation errors.
type UnsafeMarketServer interface {
	mustEmbedUnimplementedMarketServer()
}

func RegisterMarketServer(s grpc.ServiceRegistrar, srv MarketServer) {
	// If the following call panics, it indicates UnimplementedMarketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Market_ServiceDesc, srv)
}

func _Market_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_FindMaxSupplyPairInfoByTokenAddrAndChainID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).FindMaxSupplyPairInfoByTokenAddrAndChainID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_FindMaxSupplyPairInfoByTokenAddrAndChainID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).FindMaxSupplyPairInfoByTokenAddrAndChainID(ctx, req.(*PairInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_FindNearTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).FindNearTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_FindNearTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).FindNearTokenPrice(ctx, req.(*TokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_FindNearBaseTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).FindNearBaseTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_FindNearBaseTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).FindNearBaseTokenPrice(ctx, req.(*BaseTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_FindTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).FindTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_FindTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).FindTokenInfo(ctx, req.(*TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_FindPairInfoByPairAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).FindPairInfoByPairAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_FindPairInfoByPairAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).FindPairInfoByPairAddress(ctx, req.(*PairInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Market_ServiceDesc is the grpc.ServiceDesc for Market service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Market_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Market_Ping_Handler,
		},
		{
			MethodName: "FindMaxSupplyPairInfoByTokenAddrAndChainID",
			Handler:    _Market_FindMaxSupplyPairInfoByTokenAddrAndChainID_Handler,
		},
		{
			MethodName: "FindNearTokenPrice",
			Handler:    _Market_FindNearTokenPrice_Handler,
		},
		{
			MethodName: "FindNearBaseTokenPrice",
			Handler:    _Market_FindNearBaseTokenPrice_Handler,
		},
		{
			MethodName: "FindTokenInfo",
			Handler:    _Market_FindTokenInfo_Handler,
		},
		{
			MethodName: "FindPairInfoByPairAddress",
			Handler:    _Market_FindPairInfoByPairAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
