// Code generated by goctl. DO NOT EDIT!

package solmodel

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/klen-ygs/gorm-zero/gormc"
	. "github.com/klen-ygs/gorm-zero/gormc/sql"
	"gorm.io/gorm"
)

// avoid unused err
var _ = time.Second

type (
	marketKlineModel interface {
		Insert(ctx context.Context, data *MarketKline) error

		FindOne(ctx context.Context, id int64) (*MarketKline, error)
		FindOneByChainIdPairAddrIntervalValCandleTime(ctx context.Context, chainId int64, pairAddr string, intervalVal string, candleTime int64) (*MarketKline, error)
		Update(ctx context.Context, data *MarketKline) error

		Delete(ctx context.Context, id int64) error
	}

	defaultMarketKlineModel struct {
		conn  *gorm.DB
		table string
	}

	MarketKline struct {
		Id          int64     `gorm:"column:id"`
		ChainId     int64     `gorm:"column:chain_id"`
		PairAddr    string    `gorm:"column:pair_addr"`
		TokenAddr   string    `gorm:"column:token_addr"`
		IntervalVal string    `gorm:"column:interval_val"`
		CandleTime  int64     `gorm:"column:candle_time"`
		Open        float64   `gorm:"column:open"`
		High        float64   `gorm:"column:high"`
		Low         float64   `gorm:"column:low"`
		Close       float64   `gorm:"column:close"`
		McapOpen    float64   `gorm:"column:mcap_open"`
		McapHigh    float64   `gorm:"column:mcap_high"`
		McapLow     float64   `gorm:"column:mcap_low"`
		McapClose   float64   `gorm:"column:mcap_close"`
		AmountUsd   float64   `gorm:"column:amount_usd"`
		VolumeToken float64   `gorm:"column:volume_token"`
		OpenAt      int64     `gorm:"column:open_at"`
		CloseAt     int64     `gorm:"column:close_at"`
		AvgPrice    float64   `gorm:"column:avg_price"`
		TotalCount  int64     `gorm:"column:total_count"`
		BuyCount    int64     `gorm:"column:buy_count"`
		SellCount   int64     `gorm:"column:sell_count"`
		CreatedAt   time.Time `gorm:"column:created_at"`
		UpdatedAt   time.Time `gorm:"column:updated_at"`
	}
)

var QMarketKline MarketKline

func init() {
	InitField(&QMarketKline)
}

func (MarketKline) TableName() string {
	return strings.Trim("`market_kline`", "`")
}

func newMarketKlineModel(conn *gorm.DB) *defaultMarketKlineModel {
	return &defaultMarketKlineModel{
		conn:  conn,
		table: strings.Trim("`market_kline`", "`"),
	}
}

func (m *defaultMarketKlineModel) Insert(ctx context.Context, data *MarketKline) error {
	db := m.conn
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultMarketKlineModel) FindOne(ctx context.Context, id int64) (*MarketKline, error) {
	var resp MarketKline
	err := m.conn.WithContext(ctx).Model(&MarketKline{}).Where("`id` = @id", sql.Named("id", id)).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err

}

func (m *defaultMarketKlineModel) FindOneByChainIdPairAddrIntervalValCandleTime(ctx context.Context, chainId int64, pairAddr string, intervalVal string, candleTime int64) (*MarketKline, error) {
	var resp MarketKline
	err := m.conn.WithContext(ctx).Model(&MarketKline{}).Where("`chain_id` = ? and `pair_addr` = ? and `interval_val` = ? and `candle_time` = ?", chainId, pairAddr, intervalVal, candleTime).Take(&resp).Error
	if err == gormc.ErrNotFound {
		return nil, err
	}
	return &resp, err
}

func (m *defaultMarketKlineModel) Update(ctx context.Context, data *MarketKline) error {
	db := m.conn
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultMarketKlineModel) Delete(ctx context.Context, id int64) error {
	db := m.conn
	err := db.WithContext(ctx).Where("`id` = @id", sql.Named("id", id)).Delete(&MarketKline{}).Error

	return err
}
