// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AdminSetIdlAuthority is the `admin_set_idl_authority` instruction.
type AdminSetIdlAuthorityInstruction struct {
	IdlAuthority *ag_solanago.PublicKey

	// [0] = [SIGNER] authority
	//
	// [1] = [] global
	//
	// [2] = [WRITE] idl_account
	//
	// [3] = [] system_program
	//
	// [4] = [] program_signer
	//
	// [5] = [] event_authority
	//
	// [6] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAdminSetIdlAuthorityInstructionBuilder creates a new `AdminSetIdlAuthorityInstruction` instruction builder.
func NewAdminSetIdlAuthorityInstructionBuilder() *AdminSetIdlAuthorityInstruction {
	nd := &AdminSetIdlAuthorityInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	nd.AccountMetaSlice[3] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetIdlAuthority sets the "idl_authority" parameter.
func (inst *AdminSetIdlAuthorityInstruction) SetIdlAuthority(idl_authority ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.IdlAuthority = &idl_authority
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *AdminSetIdlAuthorityInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *AdminSetIdlAuthorityInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetGlobalAccount sets the "global" account.
func (inst *AdminSetIdlAuthorityInstruction) SetGlobalAccount(global ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(global)
	return inst
}

func (inst *AdminSetIdlAuthorityInstruction) findFindGlobalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalAddressWithBumpSeed calculates Global account address with given seeds and a known bump seed.
func (inst *AdminSetIdlAuthorityInstruction) FindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalAddress(bumpSeed)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalAddress finds Global account address with given seeds.
func (inst *AdminSetIdlAuthorityInstruction) FindGlobalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalAddress(0)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindGlobalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalAccount gets the "global" account.
func (inst *AdminSetIdlAuthorityInstruction) GetGlobalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetIdlAccountAccount sets the "idl_account" account.
func (inst *AdminSetIdlAuthorityInstruction) SetIdlAccountAccount(idlAccount ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(idlAccount).WRITE()
	return inst
}

// GetIdlAccountAccount gets the "idl_account" account.
func (inst *AdminSetIdlAuthorityInstruction) GetIdlAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *AdminSetIdlAuthorityInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *AdminSetIdlAuthorityInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetProgramSignerAccount sets the "program_signer" account.
func (inst *AdminSetIdlAuthorityInstruction) SetProgramSignerAccount(programSigner ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(programSigner)
	return inst
}

func (inst *AdminSetIdlAuthorityInstruction) findFindProgramSignerAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindProgramSignerAddressWithBumpSeed calculates ProgramSigner account address with given seeds and a known bump seed.
func (inst *AdminSetIdlAuthorityInstruction) FindProgramSignerAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindProgramSignerAddress(bumpSeed)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindProgramSignerAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindProgramSignerAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindProgramSignerAddress finds ProgramSigner account address with given seeds.
func (inst *AdminSetIdlAuthorityInstruction) FindProgramSignerAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindProgramSignerAddress(0)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindProgramSignerAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindProgramSignerAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetProgramSignerAccount gets the "program_signer" account.
func (inst *AdminSetIdlAuthorityInstruction) GetProgramSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *AdminSetIdlAuthorityInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *AdminSetIdlAuthorityInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *AdminSetIdlAuthorityInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *AdminSetIdlAuthorityInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *AdminSetIdlAuthorityInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *AdminSetIdlAuthorityInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetProgramAccount sets the "program" account.
func (inst *AdminSetIdlAuthorityInstruction) SetProgramAccount(program ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *AdminSetIdlAuthorityInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst AdminSetIdlAuthorityInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AdminSetIdlAuthority,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AdminSetIdlAuthorityInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AdminSetIdlAuthorityInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.IdlAuthority == nil {
			return errors.New("IdlAuthority parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Global is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.IdlAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ProgramSigner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *AdminSetIdlAuthorityInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AdminSetIdlAuthority")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" IdlAuthority", *inst.IdlAuthority))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         global", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("           idl_", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" system_program", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" program_signer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("event_authority", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        program", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj AdminSetIdlAuthorityInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `IdlAuthority` param:
	err = encoder.Encode(obj.IdlAuthority)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AdminSetIdlAuthorityInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `IdlAuthority`:
	err = decoder.Decode(&obj.IdlAuthority)
	if err != nil {
		return err
	}
	return nil
}

// NewAdminSetIdlAuthorityInstruction declares a new AdminSetIdlAuthority instruction with the provided parameters and accounts.
func NewAdminSetIdlAuthorityInstruction(
	// Parameters:
	idl_authority ag_solanago.PublicKey,
	// Accounts:
	authority ag_solanago.PublicKey,
	global ag_solanago.PublicKey,
	idlAccount ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	programSigner ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *AdminSetIdlAuthorityInstruction {
	return NewAdminSetIdlAuthorityInstructionBuilder().
		SetIdlAuthority(idl_authority).
		SetAuthorityAccount(authority).
		SetGlobalAccount(global).
		SetIdlAccountAccount(idlAccount).
		SetSystemProgramAccount(systemProgram).
		SetProgramSignerAccount(programSigner).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
