// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Given a budget of spendable SOL, buy at least min_tokens_out tokens.
// Fees are deducted from spendable_sol_in.
//
// # Quote formulas
// Where:
// - total_fee_bps = protocol_fee_bps + creator_fee_bps (creator_fee_bps is 0 if no creator)
// - floor(a/b) = a / b (integer division)
// - ceil(a/b) = (a + b - 1) / b
//
// SOL → tokens quote
// To calculate tokens_out for a given spendable_sol_in:
// 1. net_sol = floor(spendable_sol_in * 10_000 / (10_000 + total_fee_bps))
// 2. fees = ceil(net_sol * protocol_fee_bps / 10_000) + ceil(net_sol * creator_fee_bps / 10_000) (creator_fee_bps is 0 if no creator)
// 3. if net_sol + fees > spendable_sol_in: net_sol = net_sol - (net_sol + fees - spendable_sol_in)
// 4. tokens_out = floor((net_sol - 1) * virtual_token_reserves / (virtual_sol_reserves + net_sol - 1))
//
// Reverse quote (tokens → SOL)
// To calculate spendable_sol_in for a desired number of tokens:
// 1. net_sol = ceil(tokens * virtual_sol_reserves / (virtual_token_reserves - tokens)) + 1
// 2. spendable_sol_in = ceil(net_sol * (10_000 + total_fee_bps) / 10_000)
//
// Rent
// Separately make sure the instruction's payer has enough SOL to cover rent for:
// - creator_vault: rent.minimum_balance(0)
// - user_volume_accumulator: rent.minimum_balance(UserVolumeAccumulator::LEN)
type BuyExactSolInInstruction struct {
	SpendableSolIn *uint64
	MinTokensOut   *uint64
	TrackVolume    *OptionBool

	// [0] = [] global
	//
	// [1] = [WRITE] fee_recipient
	//
	// [2] = [] mint
	//
	// [3] = [WRITE] bonding_curve
	//
	// [4] = [WRITE] associated_bonding_curve
	//
	// [5] = [WRITE] associated_user
	//
	// [6] = [WRITE, SIGNER] user
	//
	// [7] = [] system_program
	//
	// [8] = [] token_program
	//
	// [9] = [WRITE] creator_vault
	//
	// [10] = [] event_authority
	//
	// [11] = [] program
	//
	// [12] = [] global_volume_accumulator
	//
	// [13] = [WRITE] user_volume_accumulator
	//
	// [14] = [] fee_config
	//
	// [15] = [] fee_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBuyExactSolInInstructionBuilder creates a new `BuyExactSolInInstruction` instruction builder.
func NewBuyExactSolInInstructionBuilder() *BuyExactSolInInstruction {
	nd := &BuyExactSolInInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 16),
	}
	nd.AccountMetaSlice[7] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	nd.AccountMetaSlice[11] = ag_solanago.Meta(Addresses["6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"])
	nd.AccountMetaSlice[15] = ag_solanago.Meta(Addresses["pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"])
	return nd
}

// SetSpendableSolIn sets the "spendable_sol_in" parameter.
func (inst *BuyExactSolInInstruction) SetSpendableSolIn(spendable_sol_in uint64) *BuyExactSolInInstruction {
	inst.SpendableSolIn = &spendable_sol_in
	return inst
}

// SetMinTokensOut sets the "min_tokens_out" parameter.
func (inst *BuyExactSolInInstruction) SetMinTokensOut(min_tokens_out uint64) *BuyExactSolInInstruction {
	inst.MinTokensOut = &min_tokens_out
	return inst
}

// SetTrackVolume sets the "track_volume" parameter.
func (inst *BuyExactSolInInstruction) SetTrackVolume(track_volume OptionBool) *BuyExactSolInInstruction {
	inst.TrackVolume = &track_volume
	return inst
}

// SetGlobalAccount sets the "global" account.
func (inst *BuyExactSolInInstruction) SetGlobalAccount(global ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(global)
	return inst
}

func (inst *BuyExactSolInInstruction) findFindGlobalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalAddressWithBumpSeed calculates Global account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalAddress(bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalAddress finds Global account address with given seeds.
func (inst *BuyExactSolInInstruction) FindGlobalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalAddress(0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindGlobalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalAccount gets the "global" account.
func (inst *BuyExactSolInInstruction) GetGlobalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFeeRecipientAccount sets the "fee_recipient" account.
func (inst *BuyExactSolInInstruction) SetFeeRecipientAccount(feeRecipient ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(feeRecipient).WRITE()
	return inst
}

// GetFeeRecipientAccount gets the "fee_recipient" account.
func (inst *BuyExactSolInInstruction) GetFeeRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintAccount sets the "mint" account.
func (inst *BuyExactSolInInstruction) SetMintAccount(mint ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *BuyExactSolInInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBondingCurveAccount sets the "bonding_curve" account.
func (inst *BuyExactSolInInstruction) SetBondingCurveAccount(bondingCurve ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(bondingCurve).WRITE()
	return inst
}

func (inst *BuyExactSolInInstruction) findFindBondingCurveAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: bonding-curve
	seeds = append(seeds, []byte{byte(0x62), byte(0x6f), byte(0x6e), byte(0x64), byte(0x69), byte(0x6e), byte(0x67), byte(0x2d), byte(0x63), byte(0x75), byte(0x72), byte(0x76), byte(0x65)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindBondingCurveAddressWithBumpSeed calculates BondingCurve account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindBondingCurveAddress(mint, bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindBondingCurveAddress finds BondingCurve account address with given seeds.
func (inst *BuyExactSolInInstruction) FindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindBondingCurveAddress(mint, 0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetBondingCurveAccount gets the "bonding_curve" account.
func (inst *BuyExactSolInInstruction) GetBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetAssociatedBondingCurveAccount sets the "associated_bonding_curve" account.
func (inst *BuyExactSolInInstruction) SetAssociatedBondingCurveAccount(associatedBondingCurve ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(associatedBondingCurve).WRITE()
	return inst
}

func (inst *BuyExactSolInInstruction) findFindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: bonding_curve
	seeds = append(seeds, bondingCurve.Bytes())
	// path: token_program
	seeds = append(seeds, tokenProgram.Bytes())
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindAssociatedBondingCurveAddressWithBumpSeed calculates AssociatedBondingCurve account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindAssociatedBondingCurveAddressWithBumpSeed(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindAssociatedBondingCurveAddressWithBumpSeed(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAssociatedBondingCurveAddress finds AssociatedBondingCurve account address with given seeds.
func (inst *BuyExactSolInInstruction) FindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, 0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAssociatedBondingCurveAccount gets the "associated_bonding_curve" account.
func (inst *BuyExactSolInInstruction) GetAssociatedBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAssociatedUserAccount sets the "associated_user" account.
func (inst *BuyExactSolInInstruction) SetAssociatedUserAccount(associatedUser ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(associatedUser).WRITE()
	return inst
}

// GetAssociatedUserAccount gets the "associated_user" account.
func (inst *BuyExactSolInInstruction) GetAssociatedUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetUserAccount sets the "user" account.
func (inst *BuyExactSolInInstruction) SetUserAccount(user ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *BuyExactSolInInstruction) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *BuyExactSolInInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *BuyExactSolInInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *BuyExactSolInInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *BuyExactSolInInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetCreatorVaultAccount sets the "creator_vault" account.
func (inst *BuyExactSolInInstruction) SetCreatorVaultAccount(creatorVault ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(creatorVault).WRITE()
	return inst
}

func (inst *BuyExactSolInInstruction) findFindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: creator-vault
	seeds = append(seeds, []byte{byte(0x63), byte(0x72), byte(0x65), byte(0x61), byte(0x74), byte(0x6f), byte(0x72), byte(0x2d), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: bonding_curve.creator
	seeds = append(seeds, bondingCurveCreator.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCreatorVaultAddressWithBumpSeed calculates CreatorVault account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindCreatorVaultAddressWithBumpSeed(bondingCurveCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCreatorVaultAddress(bondingCurveCreator, bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindCreatorVaultAddressWithBumpSeed(bondingCurveCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCreatorVaultAddress(bondingCurveCreator, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCreatorVaultAddress finds CreatorVault account address with given seeds.
func (inst *BuyExactSolInInstruction) FindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCreatorVaultAddress(bondingCurveCreator, 0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCreatorVaultAddress(bondingCurveCreator, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCreatorVaultAccount gets the "creator_vault" account.
func (inst *BuyExactSolInInstruction) GetCreatorVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *BuyExactSolInInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *BuyExactSolInInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *BuyExactSolInInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *BuyExactSolInInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetProgramAccount sets the "program" account.
func (inst *BuyExactSolInInstruction) SetProgramAccount(program ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *BuyExactSolInInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetGlobalVolumeAccumulatorAccount sets the "global_volume_accumulator" account.
func (inst *BuyExactSolInInstruction) SetGlobalVolumeAccumulatorAccount(globalVolumeAccumulator ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(globalVolumeAccumulator)
	return inst
}

func (inst *BuyExactSolInInstruction) findFindGlobalVolumeAccumulatorAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global_volume_accumulator
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c), byte(0x5f), byte(0x76), byte(0x6f), byte(0x6c), byte(0x75), byte(0x6d), byte(0x65), byte(0x5f), byte(0x61), byte(0x63), byte(0x63), byte(0x75), byte(0x6d), byte(0x75), byte(0x6c), byte(0x61), byte(0x74), byte(0x6f), byte(0x72)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalVolumeAccumulatorAddressWithBumpSeed calculates GlobalVolumeAccumulator account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindGlobalVolumeAccumulatorAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalVolumeAccumulatorAddress(bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindGlobalVolumeAccumulatorAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalVolumeAccumulatorAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalVolumeAccumulatorAddress finds GlobalVolumeAccumulator account address with given seeds.
func (inst *BuyExactSolInInstruction) FindGlobalVolumeAccumulatorAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalVolumeAccumulatorAddress(0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindGlobalVolumeAccumulatorAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalVolumeAccumulatorAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalVolumeAccumulatorAccount gets the "global_volume_accumulator" account.
func (inst *BuyExactSolInInstruction) GetGlobalVolumeAccumulatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetUserVolumeAccumulatorAccount sets the "user_volume_accumulator" account.
func (inst *BuyExactSolInInstruction) SetUserVolumeAccumulatorAccount(userVolumeAccumulator ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(userVolumeAccumulator).WRITE()
	return inst
}

func (inst *BuyExactSolInInstruction) findFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: user_volume_accumulator
	seeds = append(seeds, []byte{byte(0x75), byte(0x73), byte(0x65), byte(0x72), byte(0x5f), byte(0x76), byte(0x6f), byte(0x6c), byte(0x75), byte(0x6d), byte(0x65), byte(0x5f), byte(0x61), byte(0x63), byte(0x63), byte(0x75), byte(0x6d), byte(0x75), byte(0x6c), byte(0x61), byte(0x74), byte(0x6f), byte(0x72)})
	// path: user
	seeds = append(seeds, user.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindUserVolumeAccumulatorAddressWithBumpSeed calculates UserVolumeAccumulator account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindUserVolumeAccumulatorAddress finds UserVolumeAccumulator account address with given seeds.
func (inst *BuyExactSolInInstruction) FindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindUserVolumeAccumulatorAddress(user, 0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetUserVolumeAccumulatorAccount gets the "user_volume_accumulator" account.
func (inst *BuyExactSolInInstruction) GetUserVolumeAccumulatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetFeeConfigAccount sets the "fee_config" account.
func (inst *BuyExactSolInInstruction) SetFeeConfigAccount(feeConfig ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(feeConfig)
	return inst
}

func (inst *BuyExactSolInInstruction) findFindFeeConfigAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: fee_config
	seeds = append(seeds, []byte{byte(0x66), byte(0x65), byte(0x65), byte(0x5f), byte(0x63), byte(0x6f), byte(0x6e), byte(0x66), byte(0x69), byte(0x67)})
	// const (raw): [1 86 224 246 147 102 90 207 68 219 21 104 191 23 91 170 81 137 203 151 245 210 255 59 101 93 43 182 253 109 24 176]
	seeds = append(seeds, []byte{byte(0x1), byte(0x56), byte(0xe0), byte(0xf6), byte(0x93), byte(0x66), byte(0x5a), byte(0xcf), byte(0x44), byte(0xdb), byte(0x15), byte(0x68), byte(0xbf), byte(0x17), byte(0x5b), byte(0xaa), byte(0x51), byte(0x89), byte(0xcb), byte(0x97), byte(0xf5), byte(0xd2), byte(0xff), byte(0x3b), byte(0x65), byte(0x5d), byte(0x2b), byte(0xb6), byte(0xfd), byte(0x6d), byte(0x18), byte(0xb0)})

	programID := Addresses["pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindFeeConfigAddressWithBumpSeed calculates FeeConfig account address with given seeds and a known bump seed.
func (inst *BuyExactSolInInstruction) FindFeeConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindFeeConfigAddress(bumpSeed)
	return
}

func (inst *BuyExactSolInInstruction) MustFindFeeConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindFeeConfigAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindFeeConfigAddress finds FeeConfig account address with given seeds.
func (inst *BuyExactSolInInstruction) FindFeeConfigAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindFeeConfigAddress(0)
	return
}

func (inst *BuyExactSolInInstruction) MustFindFeeConfigAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindFeeConfigAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetFeeConfigAccount gets the "fee_config" account.
func (inst *BuyExactSolInInstruction) GetFeeConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetFeeProgramAccount sets the "fee_program" account.
func (inst *BuyExactSolInInstruction) SetFeeProgramAccount(feeProgram ag_solanago.PublicKey) *BuyExactSolInInstruction {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(feeProgram)
	return inst
}

// GetFeeProgramAccount gets the "fee_program" account.
func (inst *BuyExactSolInInstruction) GetFeeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

func (inst BuyExactSolInInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BuyExactSolIn,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BuyExactSolInInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BuyExactSolInInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.SpendableSolIn == nil {
			return errors.New("SpendableSolIn parameter is not set")
		}
		if inst.MinTokensOut == nil {
			return errors.New("MinTokensOut parameter is not set")
		}
		if inst.TrackVolume == nil {
			return errors.New("TrackVolume parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Global is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.FeeRecipient is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BondingCurve is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.AssociatedBondingCurve is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AssociatedUser is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.CreatorVault is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Program is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.GlobalVolumeAccumulator is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.UserVolumeAccumulator is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.FeeConfig is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.FeeProgram is not set")
		}
	}
	return nil
}

func (inst *BuyExactSolInInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BuyExactSolIn")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("  SpendableSolIn", *inst.SpendableSolIn))
						paramsBranch.Child(ag_format.Param("    MinTokensOut", *inst.MinTokensOut))
						paramsBranch.Child(ag_format.Param("     TrackVolume", *inst.TrackVolume))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=16]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                   global", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            fee_recipient", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                     mint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("            bonding_curve", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" associated_bonding_curve", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          associated_user", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                     user", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("           system_program", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("            token_program", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("            creator_vault", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          event_authority", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("                  program", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("global_volume_accumulator", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("  user_volume_accumulator", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("               fee_config", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("              fee_program", inst.AccountMetaSlice.Get(15)))
					})
				})
		})
}

func (obj BuyExactSolInInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `SpendableSolIn` param:
	err = encoder.Encode(obj.SpendableSolIn)
	if err != nil {
		return err
	}
	// Serialize `MinTokensOut` param:
	err = encoder.Encode(obj.MinTokensOut)
	if err != nil {
		return err
	}
	// Serialize `TrackVolume` param:
	err = encoder.Encode(obj.TrackVolume)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BuyExactSolInInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `SpendableSolIn`:
	err = decoder.Decode(&obj.SpendableSolIn)
	if err != nil {
		return err
	}
	// Deserialize `MinTokensOut`:
	err = decoder.Decode(&obj.MinTokensOut)
	if err != nil {
		return err
	}
	// Deserialize `TrackVolume`:
	err = decoder.Decode(&obj.TrackVolume)
	if err != nil {
		return err
	}
	return nil
}

// NewBuyExactSolInInstruction declares a new BuyExactSolIn instruction with the provided parameters and accounts.
func NewBuyExactSolInInstruction(
	// Parameters:
	spendable_sol_in uint64,
	min_tokens_out uint64,
	track_volume OptionBool,
	// Accounts:
	global ag_solanago.PublicKey,
	feeRecipient ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	bondingCurve ag_solanago.PublicKey,
	associatedBondingCurve ag_solanago.PublicKey,
	associatedUser ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	creatorVault ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey,
	globalVolumeAccumulator ag_solanago.PublicKey,
	userVolumeAccumulator ag_solanago.PublicKey,
	feeConfig ag_solanago.PublicKey,
	feeProgram ag_solanago.PublicKey) *BuyExactSolInInstruction {
	return NewBuyExactSolInInstructionBuilder().
		SetSpendableSolIn(spendable_sol_in).
		SetMinTokensOut(min_tokens_out).
		SetTrackVolume(track_volume).
		SetGlobalAccount(global).
		SetFeeRecipientAccount(feeRecipient).
		SetMintAccount(mint).
		SetBondingCurveAccount(bondingCurve).
		SetAssociatedBondingCurveAccount(associatedBondingCurve).
		SetAssociatedUserAccount(associatedUser).
		SetUserAccount(user).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetCreatorVaultAccount(creatorVault).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program).
		SetGlobalVolumeAccumulatorAccount(globalVolumeAccumulator).
		SetUserVolumeAccumulatorAccount(userVolumeAccumulator).
		SetFeeConfigAccount(feeConfig).
		SetFeeProgramAccount(feeProgram)
}
