// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Creates a new spl-22 coin and bonding curve.
type CreateV2Instruction struct {
	Name         *string
	Symbol       *string
	Uri          *string
	Creator      *ag_solanago.PublicKey
	IsMayhemMode *bool

	// [0] = [WRITE, SIGNER] mint
	//
	// [1] = [] mint_authority
	//
	// [2] = [WRITE] bonding_curve
	//
	// [3] = [WRITE] associated_bonding_curve
	//
	// [4] = [] global
	//
	// [5] = [WRITE, SIGNER] user
	//
	// [6] = [] system_program
	//
	// [7] = [] token_program
	//
	// [8] = [] associated_token_program
	//
	// [9] = [WRITE] mayhem_program_id
	//
	// [10] = [] global_params
	//
	// [11] = [WRITE] sol_vault
	//
	// [12] = [WRITE] mayhem_state
	//
	// [13] = [WRITE] mayhem_token_vault
	//
	// [14] = [] event_authority
	//
	// [15] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateV2InstructionBuilder creates a new `CreateV2Instruction` instruction builder.
func NewCreateV2InstructionBuilder() *CreateV2Instruction {
	nd := &CreateV2Instruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 16),
	}
	nd.AccountMetaSlice[6] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	nd.AccountMetaSlice[7] = ag_solanago.Meta(Addresses["TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"])
	nd.AccountMetaSlice[8] = ag_solanago.Meta(Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"])
	nd.AccountMetaSlice[9] = ag_solanago.Meta(Addresses["MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e"]).WRITE()
	return nd
}

// SetName sets the "name" parameter.
func (inst *CreateV2Instruction) SetName(name string) *CreateV2Instruction {
	inst.Name = &name
	return inst
}

// SetSymbol sets the "symbol" parameter.
func (inst *CreateV2Instruction) SetSymbol(symbol string) *CreateV2Instruction {
	inst.Symbol = &symbol
	return inst
}

// SetUri sets the "uri" parameter.
func (inst *CreateV2Instruction) SetUri(uri string) *CreateV2Instruction {
	inst.Uri = &uri
	return inst
}

// SetCreator sets the "creator" parameter.
func (inst *CreateV2Instruction) SetCreator(creator ag_solanago.PublicKey) *CreateV2Instruction {
	inst.Creator = &creator
	return inst
}

// SetIsMayhemMode sets the "is_mayhem_mode" parameter.
func (inst *CreateV2Instruction) SetIsMayhemMode(is_mayhem_mode bool) *CreateV2Instruction {
	inst.IsMayhemMode = &is_mayhem_mode
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *CreateV2Instruction) SetMintAccount(mint ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint).WRITE().SIGNER()
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *CreateV2Instruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMintAuthorityAccount sets the "mint_authority" account.
func (inst *CreateV2Instruction) SetMintAuthorityAccount(mintAuthority ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mintAuthority)
	return inst
}

func (inst *CreateV2Instruction) findFindMintAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: mint-authority
	seeds = append(seeds, []byte{byte(0x6d), byte(0x69), byte(0x6e), byte(0x74), byte(0x2d), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindMintAuthorityAddressWithBumpSeed calculates MintAuthority account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindMintAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindMintAuthorityAddress(bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindMintAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMintAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindMintAuthorityAddress finds MintAuthority account address with given seeds.
func (inst *CreateV2Instruction) FindMintAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindMintAuthorityAddress(0)
	return
}

func (inst *CreateV2Instruction) MustFindMintAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMintAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetMintAuthorityAccount gets the "mint_authority" account.
func (inst *CreateV2Instruction) GetMintAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBondingCurveAccount sets the "bonding_curve" account.
func (inst *CreateV2Instruction) SetBondingCurveAccount(bondingCurve ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(bondingCurve).WRITE()
	return inst
}

func (inst *CreateV2Instruction) findFindBondingCurveAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: bonding-curve
	seeds = append(seeds, []byte{byte(0x62), byte(0x6f), byte(0x6e), byte(0x64), byte(0x69), byte(0x6e), byte(0x67), byte(0x2d), byte(0x63), byte(0x75), byte(0x72), byte(0x76), byte(0x65)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindBondingCurveAddressWithBumpSeed calculates BondingCurve account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindBondingCurveAddress(mint, bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindBondingCurveAddress finds BondingCurve account address with given seeds.
func (inst *CreateV2Instruction) FindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindBondingCurveAddress(mint, 0)
	return
}

func (inst *CreateV2Instruction) MustFindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetBondingCurveAccount gets the "bonding_curve" account.
func (inst *CreateV2Instruction) GetBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAssociatedBondingCurveAccount sets the "associated_bonding_curve" account.
func (inst *CreateV2Instruction) SetAssociatedBondingCurveAccount(associatedBondingCurve ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(associatedBondingCurve).WRITE()
	return inst
}

func (inst *CreateV2Instruction) findFindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: bonding_curve
	seeds = append(seeds, bondingCurve.Bytes())
	// path: token_program
	seeds = append(seeds, tokenProgram.Bytes())
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindAssociatedBondingCurveAddressWithBumpSeed calculates AssociatedBondingCurve account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindAssociatedBondingCurveAddressWithBumpSeed(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindAssociatedBondingCurveAddressWithBumpSeed(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAssociatedBondingCurveAddress finds AssociatedBondingCurve account address with given seeds.
func (inst *CreateV2Instruction) FindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, 0)
	return
}

func (inst *CreateV2Instruction) MustFindAssociatedBondingCurveAddress(bondingCurve ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAssociatedBondingCurveAddress(bondingCurve, tokenProgram, mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAssociatedBondingCurveAccount gets the "associated_bonding_curve" account.
func (inst *CreateV2Instruction) GetAssociatedBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetGlobalAccount sets the "global" account.
func (inst *CreateV2Instruction) SetGlobalAccount(global ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(global)
	return inst
}

func (inst *CreateV2Instruction) findFindGlobalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalAddressWithBumpSeed calculates Global account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalAddress(bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalAddress finds Global account address with given seeds.
func (inst *CreateV2Instruction) FindGlobalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalAddress(0)
	return
}

func (inst *CreateV2Instruction) MustFindGlobalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalAccount gets the "global" account.
func (inst *CreateV2Instruction) GetGlobalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserAccount sets the "user" account.
func (inst *CreateV2Instruction) SetUserAccount(user ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *CreateV2Instruction) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *CreateV2Instruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *CreateV2Instruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *CreateV2Instruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *CreateV2Instruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetAssociatedTokenProgramAccount sets the "associated_token_program" account.
func (inst *CreateV2Instruction) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associated_token_program" account.
func (inst *CreateV2Instruction) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetMayhemProgramIdAccount sets the "mayhem_program_id" account.
func (inst *CreateV2Instruction) SetMayhemProgramIdAccount(mayhemProgramId ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(mayhemProgramId).WRITE()
	return inst
}

// GetMayhemProgramIdAccount gets the "mayhem_program_id" account.
func (inst *CreateV2Instruction) GetMayhemProgramIdAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetGlobalParamsAccount sets the "global_params" account.
func (inst *CreateV2Instruction) SetGlobalParamsAccount(globalParams ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(globalParams)
	return inst
}

func (inst *CreateV2Instruction) findFindGlobalParamsAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global-params
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c), byte(0x2d), byte(0x70), byte(0x61), byte(0x72), byte(0x61), byte(0x6d), byte(0x73)})

	programID := Addresses["MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindGlobalParamsAddressWithBumpSeed calculates GlobalParams account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindGlobalParamsAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalParamsAddress(bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindGlobalParamsAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalParamsAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalParamsAddress finds GlobalParams account address with given seeds.
func (inst *CreateV2Instruction) FindGlobalParamsAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalParamsAddress(0)
	return
}

func (inst *CreateV2Instruction) MustFindGlobalParamsAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalParamsAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalParamsAccount gets the "global_params" account.
func (inst *CreateV2Instruction) GetGlobalParamsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetSolVaultAccount sets the "sol_vault" account.
func (inst *CreateV2Instruction) SetSolVaultAccount(solVault ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(solVault).WRITE()
	return inst
}

func (inst *CreateV2Instruction) findFindSolVaultAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: sol-vault
	seeds = append(seeds, []byte{byte(0x73), byte(0x6f), byte(0x6c), byte(0x2d), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})

	programID := Addresses["MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindSolVaultAddressWithBumpSeed calculates SolVault account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindSolVaultAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindSolVaultAddress(bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindSolVaultAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSolVaultAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSolVaultAddress finds SolVault account address with given seeds.
func (inst *CreateV2Instruction) FindSolVaultAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindSolVaultAddress(0)
	return
}

func (inst *CreateV2Instruction) MustFindSolVaultAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSolVaultAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetSolVaultAccount gets the "sol_vault" account.
func (inst *CreateV2Instruction) GetSolVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetMayhemStateAccount sets the "mayhem_state" account.
func (inst *CreateV2Instruction) SetMayhemStateAccount(mayhemState ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(mayhemState).WRITE()
	return inst
}

func (inst *CreateV2Instruction) findFindMayhemStateAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: mayhem-state
	seeds = append(seeds, []byte{byte(0x6d), byte(0x61), byte(0x79), byte(0x68), byte(0x65), byte(0x6d), byte(0x2d), byte(0x73), byte(0x74), byte(0x61), byte(0x74), byte(0x65)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindMayhemStateAddressWithBumpSeed calculates MayhemState account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindMayhemStateAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindMayhemStateAddress(mint, bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindMayhemStateAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMayhemStateAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindMayhemStateAddress finds MayhemState account address with given seeds.
func (inst *CreateV2Instruction) FindMayhemStateAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindMayhemStateAddress(mint, 0)
	return
}

func (inst *CreateV2Instruction) MustFindMayhemStateAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMayhemStateAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetMayhemStateAccount gets the "mayhem_state" account.
func (inst *CreateV2Instruction) GetMayhemStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetMayhemTokenVaultAccount sets the "mayhem_token_vault" account.
func (inst *CreateV2Instruction) SetMayhemTokenVaultAccount(mayhemTokenVault ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(mayhemTokenVault).WRITE()
	return inst
}

// GetMayhemTokenVaultAccount gets the "mayhem_token_vault" account.
func (inst *CreateV2Instruction) GetMayhemTokenVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *CreateV2Instruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *CreateV2Instruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *CreateV2Instruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *CreateV2Instruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *CreateV2Instruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *CreateV2Instruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *CreateV2Instruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetProgramAccount sets the "program" account.
func (inst *CreateV2Instruction) SetProgramAccount(program ag_solanago.PublicKey) *CreateV2Instruction {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *CreateV2Instruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

func (inst CreateV2Instruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateV2,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateV2Instruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateV2Instruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Name == nil {
			return errors.New("Name parameter is not set")
		}
		if inst.Symbol == nil {
			return errors.New("Symbol parameter is not set")
		}
		if inst.Uri == nil {
			return errors.New("Uri parameter is not set")
		}
		if inst.Creator == nil {
			return errors.New("Creator parameter is not set")
		}
		if inst.IsMayhemMode == nil {
			return errors.New("IsMayhemMode parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MintAuthority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.BondingCurve is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.AssociatedBondingCurve is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Global is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.MayhemProgramId is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.GlobalParams is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.SolVault is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.MayhemState is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.MayhemTokenVault is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *CreateV2Instruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateV2")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("          Name", *inst.Name))
						paramsBranch.Child(ag_format.Param("        Symbol", *inst.Symbol))
						paramsBranch.Child(ag_format.Param("           Uri", *inst.Uri))
						paramsBranch.Child(ag_format.Param("       Creator", *inst.Creator))
						paramsBranch.Child(ag_format.Param("  IsMayhemMode", *inst.IsMayhemMode))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=16]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                    mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          mint_authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("           bonding_curve", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("associated_bonding_curve", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                  global", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                    user", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("          system_program", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("           token_program", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("associated_token_program", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("       mayhem_program_id", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           global_params", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("               sol_vault", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("            mayhem_state", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("      mayhem_token_vault", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("         event_authority", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("                 program", inst.AccountMetaSlice.Get(15)))
					})
				})
		})
}

func (obj CreateV2Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Symbol` param:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return err
	}
	// Serialize `Uri` param:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return err
	}
	// Serialize `Creator` param:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return err
	}
	// Serialize `IsMayhemMode` param:
	err = encoder.Encode(obj.IsMayhemMode)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CreateV2Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return err
	}
	// Deserialize `Uri`:
	err = decoder.Decode(&obj.Uri)
	if err != nil {
		return err
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return err
	}
	// Deserialize `IsMayhemMode`:
	err = decoder.Decode(&obj.IsMayhemMode)
	if err != nil {
		return err
	}
	return nil
}

// NewCreateV2Instruction declares a new CreateV2 instruction with the provided parameters and accounts.
func NewCreateV2Instruction(
	// Parameters:
	name string,
	symbol string,
	uri string,
	creator ag_solanago.PublicKey,
	is_mayhem_mode bool,
	// Accounts:
	mint ag_solanago.PublicKey,
	mintAuthority ag_solanago.PublicKey,
	bondingCurve ag_solanago.PublicKey,
	associatedBondingCurve ag_solanago.PublicKey,
	global ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	mayhemProgramId ag_solanago.PublicKey,
	globalParams ag_solanago.PublicKey,
	solVault ag_solanago.PublicKey,
	mayhemState ag_solanago.PublicKey,
	mayhemTokenVault ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *CreateV2Instruction {
	return NewCreateV2InstructionBuilder().
		SetName(name).
		SetSymbol(symbol).
		SetUri(uri).
		SetCreator(creator).
		SetIsMayhemMode(is_mayhem_mode).
		SetMintAccount(mint).
		SetMintAuthorityAccount(mintAuthority).
		SetBondingCurveAccount(bondingCurve).
		SetAssociatedBondingCurveAccount(associatedBondingCurve).
		SetGlobalAccount(global).
		SetUserAccount(user).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetMayhemProgramIdAccount(mayhemProgramId).
		SetGlobalParamsAccount(globalParams).
		SetSolVaultAccount(solVault).
		SetMayhemStateAccount(mayhemState).
		SetMayhemTokenVaultAccount(mayhemTokenVault).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
