// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Permissionless instruction to check the minimum required fees for distribution
// Returns the minimum required balance from the creator_vault and whether distribution can proceed
type GetMinimumDistributableFeeInstruction struct {

	// [0] = [] mint
	//
	// [1] = [] bonding_curve
	//
	// [2] = [] sharing_config
	//
	// [3] = [] creator_vault
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewGetMinimumDistributableFeeInstructionBuilder creates a new `GetMinimumDistributableFeeInstruction` instruction builder.
func NewGetMinimumDistributableFeeInstructionBuilder() *GetMinimumDistributableFeeInstruction {
	nd := &GetMinimumDistributableFeeInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetMintAccount sets the "mint" account.
func (inst *GetMinimumDistributableFeeInstruction) SetMintAccount(mint ag_solanago.PublicKey) *GetMinimumDistributableFeeInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *GetMinimumDistributableFeeInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBondingCurveAccount sets the "bonding_curve" account.
func (inst *GetMinimumDistributableFeeInstruction) SetBondingCurveAccount(bondingCurve ag_solanago.PublicKey) *GetMinimumDistributableFeeInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bondingCurve)
	return inst
}

func (inst *GetMinimumDistributableFeeInstruction) findFindBondingCurveAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: bonding-curve
	seeds = append(seeds, []byte{byte(0x62), byte(0x6f), byte(0x6e), byte(0x64), byte(0x69), byte(0x6e), byte(0x67), byte(0x2d), byte(0x63), byte(0x75), byte(0x72), byte(0x76), byte(0x65)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindBondingCurveAddressWithBumpSeed calculates BondingCurve account address with given seeds and a known bump seed.
func (inst *GetMinimumDistributableFeeInstruction) FindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindBondingCurveAddress(mint, bumpSeed)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindBondingCurveAddress finds BondingCurve account address with given seeds.
func (inst *GetMinimumDistributableFeeInstruction) FindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindBondingCurveAddress(mint, 0)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetBondingCurveAccount gets the "bonding_curve" account.
func (inst *GetMinimumDistributableFeeInstruction) GetBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSharingConfigAccount sets the "sharing_config" account.
func (inst *GetMinimumDistributableFeeInstruction) SetSharingConfigAccount(sharingConfig ag_solanago.PublicKey) *GetMinimumDistributableFeeInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(sharingConfig)
	return inst
}

func (inst *GetMinimumDistributableFeeInstruction) findFindSharingConfigAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: sharing-config
	seeds = append(seeds, []byte{byte(0x73), byte(0x68), byte(0x61), byte(0x72), byte(0x69), byte(0x6e), byte(0x67), byte(0x2d), byte(0x63), byte(0x6f), byte(0x6e), byte(0x66), byte(0x69), byte(0x67)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindSharingConfigAddressWithBumpSeed calculates SharingConfig account address with given seeds and a known bump seed.
func (inst *GetMinimumDistributableFeeInstruction) FindSharingConfigAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindSharingConfigAddress(mint, bumpSeed)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindSharingConfigAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSharingConfigAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSharingConfigAddress finds SharingConfig account address with given seeds.
func (inst *GetMinimumDistributableFeeInstruction) FindSharingConfigAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindSharingConfigAddress(mint, 0)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindSharingConfigAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSharingConfigAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetSharingConfigAccount gets the "sharing_config" account.
func (inst *GetMinimumDistributableFeeInstruction) GetSharingConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetCreatorVaultAccount sets the "creator_vault" account.
func (inst *GetMinimumDistributableFeeInstruction) SetCreatorVaultAccount(creatorVault ag_solanago.PublicKey) *GetMinimumDistributableFeeInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(creatorVault)
	return inst
}

func (inst *GetMinimumDistributableFeeInstruction) findFindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: creator-vault
	seeds = append(seeds, []byte{byte(0x63), byte(0x72), byte(0x65), byte(0x61), byte(0x74), byte(0x6f), byte(0x72), byte(0x2d), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: bonding_curve.creator
	seeds = append(seeds, bondingCurveCreator.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCreatorVaultAddressWithBumpSeed calculates CreatorVault account address with given seeds and a known bump seed.
func (inst *GetMinimumDistributableFeeInstruction) FindCreatorVaultAddressWithBumpSeed(bondingCurveCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCreatorVaultAddress(bondingCurveCreator, bumpSeed)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindCreatorVaultAddressWithBumpSeed(bondingCurveCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCreatorVaultAddress(bondingCurveCreator, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCreatorVaultAddress finds CreatorVault account address with given seeds.
func (inst *GetMinimumDistributableFeeInstruction) FindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCreatorVaultAddress(bondingCurveCreator, 0)
	return
}

func (inst *GetMinimumDistributableFeeInstruction) MustFindCreatorVaultAddress(bondingCurveCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCreatorVaultAddress(bondingCurveCreator, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCreatorVaultAccount gets the "creator_vault" account.
func (inst *GetMinimumDistributableFeeInstruction) GetCreatorVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst GetMinimumDistributableFeeInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_GetMinimumDistributableFee,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst GetMinimumDistributableFeeInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *GetMinimumDistributableFeeInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BondingCurve is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SharingConfig is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CreatorVault is not set")
		}
	}
	return nil
}

func (inst *GetMinimumDistributableFeeInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("GetMinimumDistributableFee")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" bonding_curve", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("sharing_config", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" creator_vault", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj GetMinimumDistributableFeeInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *GetMinimumDistributableFeeInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewGetMinimumDistributableFeeInstruction declares a new GetMinimumDistributableFee instruction with the provided parameters and accounts.
func NewGetMinimumDistributableFeeInstruction(
	// Accounts:
	mint ag_solanago.PublicKey,
	bondingCurve ag_solanago.PublicKey,
	sharingConfig ag_solanago.PublicKey,
	creatorVault ag_solanago.PublicKey) *GetMinimumDistributableFeeInstruction {
	return NewGetMinimumDistributableFeeInstructionBuilder().
		SetMintAccount(mint).
		SetBondingCurveAccount(bondingCurve).
		SetSharingConfigAccount(sharingConfig).
		SetCreatorVaultAccount(creatorVault)
}
