// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey = ag_solanago.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")

func SetProgramID(PublicKey ag_solanago.PublicKey) {
	ProgramID = PublicKey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "Pump"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	// Allows Global::admin_set_creator_authority to override the bonding curve creator
	Instruction_AdminSetCreator = ag_binary.TypeID([8]byte{69, 25, 171, 142, 57, 239, 13, 4})

	Instruction_AdminSetIdlAuthority = ag_binary.TypeID([8]byte{8, 217, 96, 231, 144, 104, 192, 5})

	Instruction_AdminUpdateTokenIncentives = ag_binary.TypeID([8]byte{209, 11, 115, 87, 213, 23, 124, 204})

	// Buys tokens from a bonding curve.
	Instruction_Buy = ag_binary.TypeID([8]byte{102, 6, 61, 18, 1, 218, 235, 234})

	// Given a budget of spendable SOL, buy at least min_tokens_out tokens.
	// Fees are deducted from spendable_sol_in.
	//
	// # Quote formulas
	// Where:
	// - total_fee_bps = protocol_fee_bps + creator_fee_bps (creator_fee_bps is 0 if no creator)
	// - floor(a/b) = a / b (integer division)
	// - ceil(a/b) = (a + b - 1) / b
	//
	// SOL → tokens quote
	// To calculate tokens_out for a given spendable_sol_in:
	// 1. net_sol = floor(spendable_sol_in * 10_000 / (10_000 + total_fee_bps))
	// 2. fees = ceil(net_sol * protocol_fee_bps / 10_000) + ceil(net_sol * creator_fee_bps / 10_000) (creator_fee_bps is 0 if no creator)
	// 3. if net_sol + fees > spendable_sol_in: net_sol = net_sol - (net_sol + fees - spendable_sol_in)
	// 4. tokens_out = floor((net_sol - 1) * virtual_token_reserves / (virtual_sol_reserves + net_sol - 1))
	//
	// Reverse quote (tokens → SOL)
	// To calculate spendable_sol_in for a desired number of tokens:
	// 1. net_sol = ceil(tokens * virtual_sol_reserves / (virtual_token_reserves - tokens)) + 1
	// 2. spendable_sol_in = ceil(net_sol * (10_000 + total_fee_bps) / 10_000)
	//
	// Rent
	// Separately make sure the instruction's payer has enough SOL to cover rent for:
	// - creator_vault: rent.minimum_balance(0)
	// - user_volume_accumulator: rent.minimum_balance(UserVolumeAccumulator::LEN)
	Instruction_BuyExactSolIn = ag_binary.TypeID([8]byte{56, 252, 116, 8, 158, 223, 205, 95})

	Instruction_ClaimTokenIncentives = ag_binary.TypeID([8]byte{16, 4, 71, 28, 204, 1, 40, 27})

	Instruction_CloseUserVolumeAccumulator = ag_binary.TypeID([8]byte{249, 69, 164, 218, 150, 103, 84, 138})

	// Collects creator_fee from creator_vault to the coin creator account
	Instruction_CollectCreatorFee = ag_binary.TypeID([8]byte{20, 22, 86, 123, 198, 28, 219, 132})

	// Creates a new coin and bonding curve.
	Instruction_Create = ag_binary.TypeID([8]byte{24, 30, 200, 40, 5, 28, 7, 119})

	// Creates a new spl-22 coin and bonding curve.
	Instruction_CreateV2 = ag_binary.TypeID([8]byte{214, 144, 76, 236, 95, 139, 49, 180})

	// Distributes creator fees to shareholders based on their share percentages
	// The creator vault needs to have at least the minimum distributable amount to distribute fees
	// This can be checked with the get_minimum_distributable_fee instruction
	Instruction_DistributeCreatorFees = ag_binary.TypeID([8]byte{165, 114, 103, 0, 121, 206, 247, 81})

	// Extends the size of program-owned accounts
	Instruction_ExtendAccount = ag_binary.TypeID([8]byte{234, 102, 194, 203, 150, 72, 62, 229})

	// Permissionless instruction to check the minimum required fees for distribution
	// Returns the minimum required balance from the creator_vault and whether distribution can proceed
	Instruction_GetMinimumDistributableFee = ag_binary.TypeID([8]byte{117, 225, 127, 202, 134, 95, 68, 35})

	Instruction_InitUserVolumeAccumulator = ag_binary.TypeID([8]byte{94, 6, 202, 115, 255, 96, 232, 183})

	// Creates the global state.
	Instruction_Initialize = ag_binary.TypeID([8]byte{175, 175, 109, 31, 13, 152, 155, 237})

	// Migrates liquidity to pump_amm if the bonding curve is complete
	Instruction_Migrate = ag_binary.TypeID([8]byte{155, 234, 231, 146, 236, 158, 162, 30})

	Instruction_MigrateBondingCurveCreator = ag_binary.TypeID([8]byte{87, 124, 52, 191, 52, 38, 214, 232})

	// Sells tokens into a bonding curve.
	Instruction_Sell = ag_binary.TypeID([8]byte{51, 230, 133, 164, 1, 127, 131, 173})

	// Allows Global::set_creator_authority to set the bonding curve creator from Metaplex metadata or input argument
	Instruction_SetCreator = ag_binary.TypeID([8]byte{254, 148, 255, 112, 207, 142, 170, 165})

	Instruction_SetMayhemVirtualParams = ag_binary.TypeID([8]byte{61, 169, 188, 191, 153, 149, 42, 97})

	// Syncs the bonding curve creator with the Metaplex metadata creator if it exists
	Instruction_SetMetaplexCreator = ag_binary.TypeID([8]byte{138, 96, 174, 217, 48, 85, 197, 246})

	// Sets the global state parameters.
	Instruction_SetParams = ag_binary.TypeID([8]byte{27, 234, 178, 52, 147, 2, 187, 141})

	Instruction_SetReservedFeeRecipients = ag_binary.TypeID([8]byte{111, 172, 162, 232, 114, 89, 213, 142})

	Instruction_SyncUserVolumeAccumulator = ag_binary.TypeID([8]byte{86, 31, 192, 87, 163, 87, 79, 238})

	Instruction_ToggleCreateV2 = ag_binary.TypeID([8]byte{28, 255, 230, 240, 172, 107, 203, 171})

	Instruction_ToggleMayhemMode = ag_binary.TypeID([8]byte{1, 9, 111, 208, 100, 31, 255, 163})

	Instruction_UpdateGlobalAuthority = ag_binary.TypeID([8]byte{227, 181, 74, 196, 208, 21, 97, 213})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_AdminSetCreator:
		return "AdminSetCreator"
	case Instruction_AdminSetIdlAuthority:
		return "AdminSetIdlAuthority"
	case Instruction_AdminUpdateTokenIncentives:
		return "AdminUpdateTokenIncentives"
	case Instruction_Buy:
		return "Buy"
	case Instruction_BuyExactSolIn:
		return "BuyExactSolIn"
	case Instruction_ClaimTokenIncentives:
		return "ClaimTokenIncentives"
	case Instruction_CloseUserVolumeAccumulator:
		return "CloseUserVolumeAccumulator"
	case Instruction_CollectCreatorFee:
		return "CollectCreatorFee"
	case Instruction_Create:
		return "Create"
	case Instruction_CreateV2:
		return "CreateV2"
	case Instruction_DistributeCreatorFees:
		return "DistributeCreatorFees"
	case Instruction_ExtendAccount:
		return "ExtendAccount"
	case Instruction_GetMinimumDistributableFee:
		return "GetMinimumDistributableFee"
	case Instruction_InitUserVolumeAccumulator:
		return "InitUserVolumeAccumulator"
	case Instruction_Initialize:
		return "Initialize"
	case Instruction_Migrate:
		return "Migrate"
	case Instruction_MigrateBondingCurveCreator:
		return "MigrateBondingCurveCreator"
	case Instruction_Sell:
		return "Sell"
	case Instruction_SetCreator:
		return "SetCreator"
	case Instruction_SetMayhemVirtualParams:
		return "SetMayhemVirtualParams"
	case Instruction_SetMetaplexCreator:
		return "SetMetaplexCreator"
	case Instruction_SetParams:
		return "SetParams"
	case Instruction_SetReservedFeeRecipients:
		return "SetReservedFeeRecipients"
	case Instruction_SyncUserVolumeAccumulator:
		return "SyncUserVolumeAccumulator"
	case Instruction_ToggleCreateV2:
		return "ToggleCreateV2"
	case Instruction_ToggleMayhemMode:
		return "ToggleMayhemMode"
	case Instruction_UpdateGlobalAuthority:
		return "UpdateGlobalAuthority"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			Name: "admin_set_creator", Type: (*AdminSetCreatorInstruction)(nil),
		},
		{
			Name: "admin_set_idl_authority", Type: (*AdminSetIdlAuthorityInstruction)(nil),
		},
		{
			Name: "admin_update_token_incentives", Type: (*AdminUpdateTokenIncentivesInstruction)(nil),
		},
		{
			Name: "buy", Type: (*BuyInstruction)(nil),
		},
		{
			Name: "buy_exact_sol_in", Type: (*BuyExactSolInInstruction)(nil),
		},
		{
			Name: "claim_token_incentives", Type: (*ClaimTokenIncentivesInstruction)(nil),
		},
		{
			Name: "close_user_volume_accumulator", Type: (*CloseUserVolumeAccumulatorInstruction)(nil),
		},
		{
			Name: "collect_creator_fee", Type: (*CollectCreatorFeeInstruction)(nil),
		},
		{
			Name: "create", Type: (*CreateInstruction)(nil),
		},
		{
			Name: "create_v2", Type: (*CreateV2Instruction)(nil),
		},
		{
			Name: "distribute_creator_fees", Type: (*DistributeCreatorFeesInstruction)(nil),
		},
		{
			Name: "extend_account", Type: (*ExtendAccountInstruction)(nil),
		},
		{
			Name: "get_minimum_distributable_fee", Type: (*GetMinimumDistributableFeeInstruction)(nil),
		},
		{
			Name: "init_user_volume_accumulator", Type: (*InitUserVolumeAccumulatorInstruction)(nil),
		},
		{
			Name: "initialize", Type: (*InitializeInstruction)(nil),
		},
		{
			Name: "migrate", Type: (*MigrateInstruction)(nil),
		},
		{
			Name: "migrate_bonding_curve_creator", Type: (*MigrateBondingCurveCreatorInstruction)(nil),
		},
		{
			Name: "sell", Type: (*SellInstruction)(nil),
		},
		{
			Name: "set_creator", Type: (*SetCreatorInstruction)(nil),
		},
		{
			Name: "set_mayhem_virtual_params", Type: (*SetMayhemVirtualParamsInstruction)(nil),
		},
		{
			Name: "set_metaplex_creator", Type: (*SetMetaplexCreatorInstruction)(nil),
		},
		{
			Name: "set_params", Type: (*SetParamsInstruction)(nil),
		},
		{
			Name: "set_reserved_fee_recipients", Type: (*SetReservedFeeRecipientsInstruction)(nil),
		},
		{
			Name: "sync_user_volume_accumulator", Type: (*SyncUserVolumeAccumulatorInstruction)(nil),
		},
		{
			Name: "toggle_create_v2", Type: (*ToggleCreateV2Instruction)(nil),
		},
		{
			Name: "toggle_mayhem_mode", Type: (*ToggleMayhemModeInstruction)(nil),
		},
		{
			Name: "update_global_authority", Type: (*UpdateGlobalAuthorityInstruction)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}

func DecodeInstructions(message *ag_solanago.Message) (instructions []*Instruction, err error) {
	for _, ins := range message.Instructions {
		var programID ag_solanago.PublicKey
		if programID, err = message.Program(ins.ProgramIDIndex); err != nil {
			return
		}
		if !programID.Equals(ProgramID) {
			continue
		}
		var accounts []*ag_solanago.AccountMeta
		if accounts, err = ins.ResolveInstructionAccounts(message); err != nil {
			return
		}
		var insDecoded *Instruction
		if insDecoded, err = DecodeInstruction(accounts, ins.Data); err != nil {
			return
		}
		instructions = append(instructions, insDecoded)
	}
	return
}
