// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetMayhemVirtualParams is the `set_mayhem_virtual_params` instruction.
type SetMayhemVirtualParamsInstruction struct {

	// [0] = [WRITE, SIGNER] sol_vault_authority
	//
	// [1] = [WRITE] mayhem_token_vault
	//
	// [2] = [] mint
	//
	// [3] = [] global
	//
	// [4] = [WRITE] bonding_curve
	//
	// [5] = [] token_program
	//
	// [6] = [] event_authority
	//
	// [7] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetMayhemVirtualParamsInstructionBuilder creates a new `SetMayhemVirtualParamsInstruction` instruction builder.
func NewSetMayhemVirtualParamsInstructionBuilder() *SetMayhemVirtualParamsInstruction {
	nd := &SetMayhemVirtualParamsInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	nd.AccountMetaSlice[5] = ag_solanago.Meta(Addresses["TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"])
	return nd
}

// SetSolVaultAuthorityAccount sets the "sol_vault_authority" account.
func (inst *SetMayhemVirtualParamsInstruction) SetSolVaultAuthorityAccount(solVaultAuthority ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(solVaultAuthority).WRITE().SIGNER()
	return inst
}

func (inst *SetMayhemVirtualParamsInstruction) findFindSolVaultAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: sol-vault
	seeds = append(seeds, []byte{byte(0x73), byte(0x6f), byte(0x6c), byte(0x2d), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})

	programID := Addresses["MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindSolVaultAuthorityAddressWithBumpSeed calculates SolVaultAuthority account address with given seeds and a known bump seed.
func (inst *SetMayhemVirtualParamsInstruction) FindSolVaultAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindSolVaultAuthorityAddress(bumpSeed)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindSolVaultAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSolVaultAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSolVaultAuthorityAddress finds SolVaultAuthority account address with given seeds.
func (inst *SetMayhemVirtualParamsInstruction) FindSolVaultAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindSolVaultAuthorityAddress(0)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindSolVaultAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSolVaultAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetSolVaultAuthorityAccount gets the "sol_vault_authority" account.
func (inst *SetMayhemVirtualParamsInstruction) GetSolVaultAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMayhemTokenVaultAccount sets the "mayhem_token_vault" account.
func (inst *SetMayhemVirtualParamsInstruction) SetMayhemTokenVaultAccount(mayhemTokenVault ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(mayhemTokenVault).WRITE()
	return inst
}

func (inst *SetMayhemVirtualParamsInstruction) findFindMayhemTokenVaultAddress(solVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: sol_vault_authority
	seeds = append(seeds, solVaultAuthority.Bytes())
	// path: token_program
	seeds = append(seeds, tokenProgram.Bytes())
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindMayhemTokenVaultAddressWithBumpSeed calculates MayhemTokenVault account address with given seeds and a known bump seed.
func (inst *SetMayhemVirtualParamsInstruction) FindMayhemTokenVaultAddressWithBumpSeed(solVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindMayhemTokenVaultAddress(solVaultAuthority, tokenProgram, mint, bumpSeed)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindMayhemTokenVaultAddressWithBumpSeed(solVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMayhemTokenVaultAddress(solVaultAuthority, tokenProgram, mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindMayhemTokenVaultAddress finds MayhemTokenVault account address with given seeds.
func (inst *SetMayhemVirtualParamsInstruction) FindMayhemTokenVaultAddress(solVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindMayhemTokenVaultAddress(solVaultAuthority, tokenProgram, mint, 0)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindMayhemTokenVaultAddress(solVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindMayhemTokenVaultAddress(solVaultAuthority, tokenProgram, mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetMayhemTokenVaultAccount gets the "mayhem_token_vault" account.
func (inst *SetMayhemVirtualParamsInstruction) GetMayhemTokenVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMintAccount sets the "mint" account.
func (inst *SetMayhemVirtualParamsInstruction) SetMintAccount(mint ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *SetMayhemVirtualParamsInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetGlobalAccount sets the "global" account.
func (inst *SetMayhemVirtualParamsInstruction) SetGlobalAccount(global ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(global)
	return inst
}

func (inst *SetMayhemVirtualParamsInstruction) findFindGlobalAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalAddressWithBumpSeed calculates Global account address with given seeds and a known bump seed.
func (inst *SetMayhemVirtualParamsInstruction) FindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalAddress(bumpSeed)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindGlobalAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalAddress finds Global account address with given seeds.
func (inst *SetMayhemVirtualParamsInstruction) FindGlobalAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalAddress(0)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindGlobalAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalAccount gets the "global" account.
func (inst *SetMayhemVirtualParamsInstruction) GetGlobalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetBondingCurveAccount sets the "bonding_curve" account.
func (inst *SetMayhemVirtualParamsInstruction) SetBondingCurveAccount(bondingCurve ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(bondingCurve).WRITE()
	return inst
}

func (inst *SetMayhemVirtualParamsInstruction) findFindBondingCurveAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: bonding-curve
	seeds = append(seeds, []byte{byte(0x62), byte(0x6f), byte(0x6e), byte(0x64), byte(0x69), byte(0x6e), byte(0x67), byte(0x2d), byte(0x63), byte(0x75), byte(0x72), byte(0x76), byte(0x65)})
	// path: mint
	seeds = append(seeds, mint.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindBondingCurveAddressWithBumpSeed calculates BondingCurve account address with given seeds and a known bump seed.
func (inst *SetMayhemVirtualParamsInstruction) FindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindBondingCurveAddress(mint, bumpSeed)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindBondingCurveAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindBondingCurveAddress finds BondingCurve account address with given seeds.
func (inst *SetMayhemVirtualParamsInstruction) FindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindBondingCurveAddress(mint, 0)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindBondingCurveAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindBondingCurveAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetBondingCurveAccount gets the "bonding_curve" account.
func (inst *SetMayhemVirtualParamsInstruction) GetBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *SetMayhemVirtualParamsInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *SetMayhemVirtualParamsInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *SetMayhemVirtualParamsInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *SetMayhemVirtualParamsInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *SetMayhemVirtualParamsInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *SetMayhemVirtualParamsInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *SetMayhemVirtualParamsInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *SetMayhemVirtualParamsInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetProgramAccount sets the "program" account.
func (inst *SetMayhemVirtualParamsInstruction) SetProgramAccount(program ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *SetMayhemVirtualParamsInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst SetMayhemVirtualParamsInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetMayhemVirtualParams,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetMayhemVirtualParamsInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetMayhemVirtualParamsInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.SolVaultAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MayhemTokenVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Global is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.BondingCurve is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *SetMayhemVirtualParamsInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetMayhemVirtualParams")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("sol_vault_authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" mayhem_token_vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("               mint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             global", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("      bonding_curve", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("      token_program", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("    event_authority", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("            program", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj SetMayhemVirtualParamsInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *SetMayhemVirtualParamsInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewSetMayhemVirtualParamsInstruction declares a new SetMayhemVirtualParams instruction with the provided parameters and accounts.
func NewSetMayhemVirtualParamsInstruction(
	// Accounts:
	solVaultAuthority ag_solanago.PublicKey,
	mayhemTokenVault ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	global ag_solanago.PublicKey,
	bondingCurve ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *SetMayhemVirtualParamsInstruction {
	return NewSetMayhemVirtualParamsInstructionBuilder().
		SetSolVaultAuthorityAccount(solVaultAuthority).
		SetMayhemTokenVaultAccount(mayhemTokenVault).
		SetMintAccount(mint).
		SetGlobalAccount(global).
		SetBondingCurveAccount(bondingCurve).
		SetTokenProgramAccount(tokenProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
