// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpamm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AdminUpdateTokenIncentives is the `admin_update_token_incentives` instruction.
type AdminUpdateTokenIncentivesInstruction struct {
	StartTime         *int64
	EndTime           *int64
	SecondsInADay     *int64
	DayNumber         *uint64
	TokenSupplyPerDay *uint64

	// [0] = [WRITE, SIGNER] admin
	//
	// [1] = [] global_config
	//
	// [2] = [WRITE] global_volume_accumulator
	//
	// [3] = [] mint
	//
	// [4] = [WRITE] global_incentive_token_account
	//
	// [5] = [] associated_token_program
	//
	// [6] = [] system_program
	//
	// [7] = [] token_program
	//
	// [8] = [] event_authority
	//
	// [9] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAdminUpdateTokenIncentivesInstructionBuilder creates a new `AdminUpdateTokenIncentivesInstruction` instruction builder.
func NewAdminUpdateTokenIncentivesInstructionBuilder() *AdminUpdateTokenIncentivesInstruction {
	nd := &AdminUpdateTokenIncentivesInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	nd.AccountMetaSlice[5] = ag_solanago.Meta(Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"])
	nd.AccountMetaSlice[6] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetStartTime sets the "start_time" parameter.
func (inst *AdminUpdateTokenIncentivesInstruction) SetStartTime(start_time int64) *AdminUpdateTokenIncentivesInstruction {
	inst.StartTime = &start_time
	return inst
}

// SetEndTime sets the "end_time" parameter.
func (inst *AdminUpdateTokenIncentivesInstruction) SetEndTime(end_time int64) *AdminUpdateTokenIncentivesInstruction {
	inst.EndTime = &end_time
	return inst
}

// SetSecondsInADay sets the "seconds_in_a_day" parameter.
func (inst *AdminUpdateTokenIncentivesInstruction) SetSecondsInADay(seconds_in_a_day int64) *AdminUpdateTokenIncentivesInstruction {
	inst.SecondsInADay = &seconds_in_a_day
	return inst
}

// SetDayNumber sets the "day_number" parameter.
func (inst *AdminUpdateTokenIncentivesInstruction) SetDayNumber(day_number uint64) *AdminUpdateTokenIncentivesInstruction {
	inst.DayNumber = &day_number
	return inst
}

// SetTokenSupplyPerDay sets the "token_supply_per_day" parameter.
func (inst *AdminUpdateTokenIncentivesInstruction) SetTokenSupplyPerDay(token_supply_per_day uint64) *AdminUpdateTokenIncentivesInstruction {
	inst.TokenSupplyPerDay = &token_supply_per_day
	return inst
}

// SetAdminAccount sets the "admin" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetAdminAccount(admin ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(admin).WRITE().SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetGlobalConfigAccount sets the "global_config" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetGlobalConfigAccount(globalConfig ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(globalConfig)
	return inst
}

func (inst *AdminUpdateTokenIncentivesInstruction) findFindGlobalConfigAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global_config
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c), byte(0x5f), byte(0x63), byte(0x6f), byte(0x6e), byte(0x66), byte(0x69), byte(0x67)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalConfigAddressWithBumpSeed calculates GlobalConfig account address with given seeds and a known bump seed.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalConfigAddress(bumpSeed)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalConfigAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalConfigAddress finds GlobalConfig account address with given seeds.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalConfigAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalConfigAddress(0)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalConfigAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalConfigAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalConfigAccount gets the "global_config" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetGlobalConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetGlobalVolumeAccumulatorAccount sets the "global_volume_accumulator" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetGlobalVolumeAccumulatorAccount(globalVolumeAccumulator ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(globalVolumeAccumulator).WRITE()
	return inst
}

func (inst *AdminUpdateTokenIncentivesInstruction) findFindGlobalVolumeAccumulatorAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: global_volume_accumulator
	seeds = append(seeds, []byte{byte(0x67), byte(0x6c), byte(0x6f), byte(0x62), byte(0x61), byte(0x6c), byte(0x5f), byte(0x76), byte(0x6f), byte(0x6c), byte(0x75), byte(0x6d), byte(0x65), byte(0x5f), byte(0x61), byte(0x63), byte(0x63), byte(0x75), byte(0x6d), byte(0x75), byte(0x6c), byte(0x61), byte(0x74), byte(0x6f), byte(0x72)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindGlobalVolumeAccumulatorAddressWithBumpSeed calculates GlobalVolumeAccumulator account address with given seeds and a known bump seed.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalVolumeAccumulatorAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalVolumeAccumulatorAddress(bumpSeed)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalVolumeAccumulatorAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalVolumeAccumulatorAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalVolumeAccumulatorAddress finds GlobalVolumeAccumulator account address with given seeds.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalVolumeAccumulatorAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalVolumeAccumulatorAddress(0)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalVolumeAccumulatorAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalVolumeAccumulatorAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalVolumeAccumulatorAccount gets the "global_volume_accumulator" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetGlobalVolumeAccumulatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMintAccount sets the "mint" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetMintAccount(mint ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetGlobalIncentiveTokenAccountAccount sets the "global_incentive_token_account" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetGlobalIncentiveTokenAccountAccount(globalIncentiveTokenAccount ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(globalIncentiveTokenAccount).WRITE()
	return inst
}

func (inst *AdminUpdateTokenIncentivesInstruction) findFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: global_volume_accumulator
	seeds = append(seeds, globalVolumeAccumulator.Bytes())
	// path: token_program
	seeds = append(seeds, tokenProgram.Bytes())
	// path: mint
	seeds = append(seeds, mint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindGlobalIncentiveTokenAccountAddressWithBumpSeed calculates GlobalIncentiveTokenAccount account address with given seeds and a known bump seed.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalIncentiveTokenAccountAddressWithBumpSeed(globalVolumeAccumulator ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator, tokenProgram, mint, bumpSeed)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalIncentiveTokenAccountAddressWithBumpSeed(globalVolumeAccumulator ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator, tokenProgram, mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindGlobalIncentiveTokenAccountAddress finds GlobalIncentiveTokenAccount account address with given seeds.
func (inst *AdminUpdateTokenIncentivesInstruction) FindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator, tokenProgram, mint, 0)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindGlobalIncentiveTokenAccountAddress(globalVolumeAccumulator, tokenProgram, mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetGlobalIncentiveTokenAccountAccount gets the "global_incentive_token_account" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetGlobalIncentiveTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAssociatedTokenProgramAccount sets the "associated_token_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associated_token_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *AdminUpdateTokenIncentivesInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *AdminUpdateTokenIncentivesInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *AdminUpdateTokenIncentivesInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *AdminUpdateTokenIncentivesInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetProgramAccount sets the "program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) SetProgramAccount(program ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *AdminUpdateTokenIncentivesInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst AdminUpdateTokenIncentivesInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AdminUpdateTokenIncentives,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AdminUpdateTokenIncentivesInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AdminUpdateTokenIncentivesInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StartTime == nil {
			return errors.New("StartTime parameter is not set")
		}
		if inst.EndTime == nil {
			return errors.New("EndTime parameter is not set")
		}
		if inst.SecondsInADay == nil {
			return errors.New("SecondsInADay parameter is not set")
		}
		if inst.DayNumber == nil {
			return errors.New("DayNumber parameter is not set")
		}
		if inst.TokenSupplyPerDay == nil {
			return errors.New("TokenSupplyPerDay parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.GlobalConfig is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.GlobalVolumeAccumulator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.GlobalIncentiveTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *AdminUpdateTokenIncentivesInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AdminUpdateTokenIncentives")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("           StartTime", *inst.StartTime))
						paramsBranch.Child(ag_format.Param("             EndTime", *inst.EndTime))
						paramsBranch.Child(ag_format.Param("       SecondsInADay", *inst.SecondsInADay))
						paramsBranch.Child(ag_format.Param("           DayNumber", *inst.DayNumber))
						paramsBranch.Child(ag_format.Param("   TokenSupplyPerDay", *inst.TokenSupplyPerDay))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                    admin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            global_config", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("global_volume_accumulator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                     mint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("  global_incentive_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta(" associated_token_program", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           system_program", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("            token_program", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("          event_authority", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                  program", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj AdminUpdateTokenIncentivesInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StartTime` param:
	err = encoder.Encode(obj.StartTime)
	if err != nil {
		return err
	}
	// Serialize `EndTime` param:
	err = encoder.Encode(obj.EndTime)
	if err != nil {
		return err
	}
	// Serialize `SecondsInADay` param:
	err = encoder.Encode(obj.SecondsInADay)
	if err != nil {
		return err
	}
	// Serialize `DayNumber` param:
	err = encoder.Encode(obj.DayNumber)
	if err != nil {
		return err
	}
	// Serialize `TokenSupplyPerDay` param:
	err = encoder.Encode(obj.TokenSupplyPerDay)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AdminUpdateTokenIncentivesInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StartTime`:
	err = decoder.Decode(&obj.StartTime)
	if err != nil {
		return err
	}
	// Deserialize `EndTime`:
	err = decoder.Decode(&obj.EndTime)
	if err != nil {
		return err
	}
	// Deserialize `SecondsInADay`:
	err = decoder.Decode(&obj.SecondsInADay)
	if err != nil {
		return err
	}
	// Deserialize `DayNumber`:
	err = decoder.Decode(&obj.DayNumber)
	if err != nil {
		return err
	}
	// Deserialize `TokenSupplyPerDay`:
	err = decoder.Decode(&obj.TokenSupplyPerDay)
	if err != nil {
		return err
	}
	return nil
}

// NewAdminUpdateTokenIncentivesInstruction declares a new AdminUpdateTokenIncentives instruction with the provided parameters and accounts.
func NewAdminUpdateTokenIncentivesInstruction(
	// Parameters:
	start_time int64,
	end_time int64,
	seconds_in_a_day int64,
	day_number uint64,
	token_supply_per_day uint64,
	// Accounts:
	admin ag_solanago.PublicKey,
	globalConfig ag_solanago.PublicKey,
	globalVolumeAccumulator ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	globalIncentiveTokenAccount ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *AdminUpdateTokenIncentivesInstruction {
	return NewAdminUpdateTokenIncentivesInstructionBuilder().
		SetStartTime(start_time).
		SetEndTime(end_time).
		SetSecondsInADay(seconds_in_a_day).
		SetDayNumber(day_number).
		SetTokenSupplyPerDay(token_supply_per_day).
		SetAdminAccount(admin).
		SetGlobalConfigAccount(globalConfig).
		SetGlobalVolumeAccumulatorAccount(globalVolumeAccumulator).
		SetMintAccount(mint).
		SetGlobalIncentiveTokenAccountAccount(globalIncentiveTokenAccount).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
