// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpamm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CloseUserVolumeAccumulator is the `close_user_volume_accumulator` instruction.
type CloseUserVolumeAccumulatorInstruction struct {

	// [0] = [WRITE, SIGNER] user
	//
	// [1] = [WRITE] user_volume_accumulator
	//
	// [2] = [] event_authority
	//
	// [3] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCloseUserVolumeAccumulatorInstructionBuilder creates a new `CloseUserVolumeAccumulatorInstruction` instruction builder.
func NewCloseUserVolumeAccumulatorInstructionBuilder() *CloseUserVolumeAccumulatorInstruction {
	nd := &CloseUserVolumeAccumulatorInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetUserAccount sets the "user" account.
func (inst *CloseUserVolumeAccumulatorInstruction) SetUserAccount(user ag_solanago.PublicKey) *CloseUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *CloseUserVolumeAccumulatorInstruction) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserVolumeAccumulatorAccount sets the "user_volume_accumulator" account.
func (inst *CloseUserVolumeAccumulatorInstruction) SetUserVolumeAccumulatorAccount(userVolumeAccumulator ag_solanago.PublicKey) *CloseUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(userVolumeAccumulator).WRITE()
	return inst
}

func (inst *CloseUserVolumeAccumulatorInstruction) findFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: user_volume_accumulator
	seeds = append(seeds, []byte{byte(0x75), byte(0x73), byte(0x65), byte(0x72), byte(0x5f), byte(0x76), byte(0x6f), byte(0x6c), byte(0x75), byte(0x6d), byte(0x65), byte(0x5f), byte(0x61), byte(0x63), byte(0x63), byte(0x75), byte(0x6d), byte(0x75), byte(0x6c), byte(0x61), byte(0x74), byte(0x6f), byte(0x72)})
	// path: user
	seeds = append(seeds, user.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindUserVolumeAccumulatorAddressWithBumpSeed calculates UserVolumeAccumulator account address with given seeds and a known bump seed.
func (inst *CloseUserVolumeAccumulatorInstruction) FindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	return
}

func (inst *CloseUserVolumeAccumulatorInstruction) MustFindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindUserVolumeAccumulatorAddress finds UserVolumeAccumulator account address with given seeds.
func (inst *CloseUserVolumeAccumulatorInstruction) FindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindUserVolumeAccumulatorAddress(user, 0)
	return
}

func (inst *CloseUserVolumeAccumulatorInstruction) MustFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetUserVolumeAccumulatorAccount gets the "user_volume_accumulator" account.
func (inst *CloseUserVolumeAccumulatorInstruction) GetUserVolumeAccumulatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *CloseUserVolumeAccumulatorInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *CloseUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *CloseUserVolumeAccumulatorInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *CloseUserVolumeAccumulatorInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *CloseUserVolumeAccumulatorInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *CloseUserVolumeAccumulatorInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *CloseUserVolumeAccumulatorInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *CloseUserVolumeAccumulatorInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetProgramAccount sets the "program" account.
func (inst *CloseUserVolumeAccumulatorInstruction) SetProgramAccount(program ag_solanago.PublicKey) *CloseUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *CloseUserVolumeAccumulatorInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst CloseUserVolumeAccumulatorInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CloseUserVolumeAccumulator,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CloseUserVolumeAccumulatorInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CloseUserVolumeAccumulatorInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.UserVolumeAccumulator is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *CloseUserVolumeAccumulatorInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CloseUserVolumeAccumulator")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                   user", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("user_volume_accumulator", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        event_authority", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                program", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj CloseUserVolumeAccumulatorInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CloseUserVolumeAccumulatorInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCloseUserVolumeAccumulatorInstruction declares a new CloseUserVolumeAccumulator instruction with the provided parameters and accounts.
func NewCloseUserVolumeAccumulatorInstruction(
	// Accounts:
	user ag_solanago.PublicKey,
	userVolumeAccumulator ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *CloseUserVolumeAccumulatorInstruction {
	return NewCloseUserVolumeAccumulatorInstructionBuilder().
		SetUserAccount(user).
		SetUserVolumeAccumulatorAccount(userVolumeAccumulator).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
