// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpamm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitUserVolumeAccumulator is the `init_user_volume_accumulator` instruction.
type InitUserVolumeAccumulatorInstruction struct {

	// [0] = [WRITE, SIGNER] payer
	//
	// [1] = [] user
	//
	// [2] = [WRITE] user_volume_accumulator
	//
	// [3] = [] system_program
	//
	// [4] = [] event_authority
	//
	// [5] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitUserVolumeAccumulatorInstructionBuilder creates a new `InitUserVolumeAccumulatorInstruction` instruction builder.
func NewInitUserVolumeAccumulatorInstructionBuilder() *InitUserVolumeAccumulatorInstruction {
	nd := &InitUserVolumeAccumulatorInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	nd.AccountMetaSlice[3] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetPayerAccount sets the "payer" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetPayerAccount(payer ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserAccount sets the "user" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetUserAccount(user ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(user)
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserVolumeAccumulatorAccount sets the "user_volume_accumulator" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetUserVolumeAccumulatorAccount(userVolumeAccumulator ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(userVolumeAccumulator).WRITE()
	return inst
}

func (inst *InitUserVolumeAccumulatorInstruction) findFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: user_volume_accumulator
	seeds = append(seeds, []byte{byte(0x75), byte(0x73), byte(0x65), byte(0x72), byte(0x5f), byte(0x76), byte(0x6f), byte(0x6c), byte(0x75), byte(0x6d), byte(0x65), byte(0x5f), byte(0x61), byte(0x63), byte(0x63), byte(0x75), byte(0x6d), byte(0x75), byte(0x6c), byte(0x61), byte(0x74), byte(0x6f), byte(0x72)})
	// path: user
	seeds = append(seeds, user.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindUserVolumeAccumulatorAddressWithBumpSeed calculates UserVolumeAccumulator account address with given seeds and a known bump seed.
func (inst *InitUserVolumeAccumulatorInstruction) FindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	return
}

func (inst *InitUserVolumeAccumulatorInstruction) MustFindUserVolumeAccumulatorAddressWithBumpSeed(user ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindUserVolumeAccumulatorAddress finds UserVolumeAccumulator account address with given seeds.
func (inst *InitUserVolumeAccumulatorInstruction) FindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindUserVolumeAccumulatorAddress(user, 0)
	return
}

func (inst *InitUserVolumeAccumulatorInstruction) MustFindUserVolumeAccumulatorAddress(user ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindUserVolumeAccumulatorAddress(user, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetUserVolumeAccumulatorAccount gets the "user_volume_accumulator" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetUserVolumeAccumulatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *InitUserVolumeAccumulatorInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *InitUserVolumeAccumulatorInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *InitUserVolumeAccumulatorInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *InitUserVolumeAccumulatorInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *InitUserVolumeAccumulatorInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetProgramAccount sets the "program" account.
func (inst *InitUserVolumeAccumulatorInstruction) SetProgramAccount(program ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *InitUserVolumeAccumulatorInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst InitUserVolumeAccumulatorInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitUserVolumeAccumulator,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitUserVolumeAccumulatorInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitUserVolumeAccumulatorInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UserVolumeAccumulator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *InitUserVolumeAccumulatorInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitUserVolumeAccumulator")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                  payer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                   user", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("user_volume_accumulator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("         system_program", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        event_authority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                program", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj InitUserVolumeAccumulatorInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *InitUserVolumeAccumulatorInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewInitUserVolumeAccumulatorInstruction declares a new InitUserVolumeAccumulator instruction with the provided parameters and accounts.
func NewInitUserVolumeAccumulatorInstruction(
	// Accounts:
	payer ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	userVolumeAccumulator ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *InitUserVolumeAccumulatorInstruction {
	return NewInitUserVolumeAccumulatorInstructionBuilder().
		SetPayerAccount(payer).
		SetUserAccount(user).
		SetUserVolumeAccumulatorAccount(userVolumeAccumulator).
		SetSystemProgramAccount(systemProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
