// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpamm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Sell is the `sell` instruction.
type SellInstruction struct {
	BaseAmountIn      *uint64
	MinQuoteAmountOut *uint64

	// [0] = [WRITE] pool
	//
	// [1] = [WRITE, SIGNER] user
	//
	// [2] = [] global_config
	//
	// [3] = [] base_mint
	//
	// [4] = [] quote_mint
	//
	// [5] = [WRITE] user_base_token_account
	//
	// [6] = [WRITE] user_quote_token_account
	//
	// [7] = [WRITE] pool_base_token_account
	//
	// [8] = [WRITE] pool_quote_token_account
	//
	// [9] = [] protocol_fee_recipient
	//
	// [10] = [WRITE] protocol_fee_recipient_token_account
	//
	// [11] = [] base_token_program
	//
	// [12] = [] quote_token_program
	//
	// [13] = [] system_program
	//
	// [14] = [] associated_token_program
	//
	// [15] = [] event_authority
	//
	// [16] = [] program
	//
	// [17] = [WRITE] coin_creator_vault_ata
	//
	// [18] = [] coin_creator_vault_authority
	//
	// [19] = [] fee_config
	//
	// [20] = [] fee_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSellInstructionBuilder creates a new `SellInstruction` instruction builder.
func NewSellInstructionBuilder() *SellInstruction {
	nd := &SellInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 21),
	}
	nd.AccountMetaSlice[13] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	nd.AccountMetaSlice[14] = ag_solanago.Meta(Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"])
	nd.AccountMetaSlice[16] = ag_solanago.Meta(Addresses["pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"])
	nd.AccountMetaSlice[20] = ag_solanago.Meta(Addresses["pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"])
	return nd
}

// SetBaseAmountIn sets the "base_amount_in" parameter.
func (inst *SellInstruction) SetBaseAmountIn(base_amount_in uint64) *SellInstruction {
	inst.BaseAmountIn = &base_amount_in
	return inst
}

// SetMinQuoteAmountOut sets the "min_quote_amount_out" parameter.
func (inst *SellInstruction) SetMinQuoteAmountOut(min_quote_amount_out uint64) *SellInstruction {
	inst.MinQuoteAmountOut = &min_quote_amount_out
	return inst
}

// SetPoolAccount sets the "pool" account.
func (inst *SellInstruction) SetPoolAccount(pool ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(pool).WRITE()
	return inst
}

// GetPoolAccount gets the "pool" account.
func (inst *SellInstruction) GetPoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserAccount sets the "user" account.
func (inst *SellInstruction) SetUserAccount(user ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *SellInstruction) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetGlobalConfigAccount sets the "global_config" account.
func (inst *SellInstruction) SetGlobalConfigAccount(globalConfig ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(globalConfig)
	return inst
}

// GetGlobalConfigAccount gets the "global_config" account.
func (inst *SellInstruction) GetGlobalConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBaseMintAccount sets the "base_mint" account.
func (inst *SellInstruction) SetBaseMintAccount(baseMint ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(baseMint)
	return inst
}

// GetBaseMintAccount gets the "base_mint" account.
func (inst *SellInstruction) GetBaseMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetQuoteMintAccount sets the "quote_mint" account.
func (inst *SellInstruction) SetQuoteMintAccount(quoteMint ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(quoteMint)
	return inst
}

// GetQuoteMintAccount gets the "quote_mint" account.
func (inst *SellInstruction) GetQuoteMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserBaseTokenAccountAccount sets the "user_base_token_account" account.
func (inst *SellInstruction) SetUserBaseTokenAccountAccount(userBaseTokenAccount ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userBaseTokenAccount).WRITE()
	return inst
}

// GetUserBaseTokenAccountAccount gets the "user_base_token_account" account.
func (inst *SellInstruction) GetUserBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetUserQuoteTokenAccountAccount sets the "user_quote_token_account" account.
func (inst *SellInstruction) SetUserQuoteTokenAccountAccount(userQuoteTokenAccount ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(userQuoteTokenAccount).WRITE()
	return inst
}

// GetUserQuoteTokenAccountAccount gets the "user_quote_token_account" account.
func (inst *SellInstruction) GetUserQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPoolBaseTokenAccountAccount sets the "pool_base_token_account" account.
func (inst *SellInstruction) SetPoolBaseTokenAccountAccount(poolBaseTokenAccount ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(poolBaseTokenAccount).WRITE()
	return inst
}

// GetPoolBaseTokenAccountAccount gets the "pool_base_token_account" account.
func (inst *SellInstruction) GetPoolBaseTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetPoolQuoteTokenAccountAccount sets the "pool_quote_token_account" account.
func (inst *SellInstruction) SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(poolQuoteTokenAccount).WRITE()
	return inst
}

// GetPoolQuoteTokenAccountAccount gets the "pool_quote_token_account" account.
func (inst *SellInstruction) GetPoolQuoteTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetProtocolFeeRecipientAccount sets the "protocol_fee_recipient" account.
func (inst *SellInstruction) SetProtocolFeeRecipientAccount(protocolFeeRecipient ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(protocolFeeRecipient)
	return inst
}

// GetProtocolFeeRecipientAccount gets the "protocol_fee_recipient" account.
func (inst *SellInstruction) GetProtocolFeeRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetProtocolFeeRecipientTokenAccountAccount sets the "protocol_fee_recipient_token_account" account.
func (inst *SellInstruction) SetProtocolFeeRecipientTokenAccountAccount(protocolFeeRecipientTokenAccount ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(protocolFeeRecipientTokenAccount).WRITE()
	return inst
}

func (inst *SellInstruction) findFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: protocol_fee_recipient
	seeds = append(seeds, protocolFeeRecipient.Bytes())
	// path: quote_token_program
	seeds = append(seeds, quoteTokenProgram.Bytes())
	// path: quote_mint
	seeds = append(seeds, quoteMint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindProtocolFeeRecipientTokenAccountAddressWithBumpSeed calculates ProtocolFeeRecipientTokenAccount account address with given seeds and a known bump seed.
func (inst *SellInstruction) FindProtocolFeeRecipientTokenAccountAddressWithBumpSeed(protocolFeeRecipient ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient, quoteTokenProgram, quoteMint, bumpSeed)
	return
}

func (inst *SellInstruction) MustFindProtocolFeeRecipientTokenAccountAddressWithBumpSeed(protocolFeeRecipient ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient, quoteTokenProgram, quoteMint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindProtocolFeeRecipientTokenAccountAddress finds ProtocolFeeRecipientTokenAccount account address with given seeds.
func (inst *SellInstruction) FindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient, quoteTokenProgram, quoteMint, 0)
	return
}

func (inst *SellInstruction) MustFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindProtocolFeeRecipientTokenAccountAddress(protocolFeeRecipient, quoteTokenProgram, quoteMint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetProtocolFeeRecipientTokenAccountAccount gets the "protocol_fee_recipient_token_account" account.
func (inst *SellInstruction) GetProtocolFeeRecipientTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetBaseTokenProgramAccount sets the "base_token_program" account.
func (inst *SellInstruction) SetBaseTokenProgramAccount(baseTokenProgram ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(baseTokenProgram)
	return inst
}

// GetBaseTokenProgramAccount gets the "base_token_program" account.
func (inst *SellInstruction) GetBaseTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetQuoteTokenProgramAccount sets the "quote_token_program" account.
func (inst *SellInstruction) SetQuoteTokenProgramAccount(quoteTokenProgram ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(quoteTokenProgram)
	return inst
}

// GetQuoteTokenProgramAccount gets the "quote_token_program" account.
func (inst *SellInstruction) GetQuoteTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *SellInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *SellInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetAssociatedTokenProgramAccount sets the "associated_token_program" account.
func (inst *SellInstruction) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associated_token_program" account.
func (inst *SellInstruction) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *SellInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *SellInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *SellInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *SellInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *SellInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *SellInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *SellInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

// SetProgramAccount sets the "program" account.
func (inst *SellInstruction) SetProgramAccount(program ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[16] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *SellInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(16)
}

// SetCoinCreatorVaultAtaAccount sets the "coin_creator_vault_ata" account.
func (inst *SellInstruction) SetCoinCreatorVaultAtaAccount(coinCreatorVaultAta ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[17] = ag_solanago.Meta(coinCreatorVaultAta).WRITE()
	return inst
}

func (inst *SellInstruction) findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: coin_creator_vault_authority
	seeds = append(seeds, coinCreatorVaultAuthority.Bytes())
	// path: quote_token_program
	seeds = append(seeds, quoteTokenProgram.Bytes())
	// path: quote_mint
	seeds = append(seeds, quoteMint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindCoinCreatorVaultAtaAddressWithBumpSeed calculates CoinCreatorVaultAta account address with given seeds and a known bump seed.
func (inst *SellInstruction) FindCoinCreatorVaultAtaAddressWithBumpSeed(coinCreatorVaultAuthority ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, quoteTokenProgram, quoteMint, bumpSeed)
	return
}

func (inst *SellInstruction) MustFindCoinCreatorVaultAtaAddressWithBumpSeed(coinCreatorVaultAuthority ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, quoteTokenProgram, quoteMint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCoinCreatorVaultAtaAddress finds CoinCreatorVaultAta account address with given seeds.
func (inst *SellInstruction) FindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, quoteTokenProgram, quoteMint, 0)
	return
}

func (inst *SellInstruction) MustFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, quoteTokenProgram ag_solanago.PublicKey, quoteMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, quoteTokenProgram, quoteMint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCoinCreatorVaultAtaAccount gets the "coin_creator_vault_ata" account.
func (inst *SellInstruction) GetCoinCreatorVaultAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(17)
}

// SetCoinCreatorVaultAuthorityAccount sets the "coin_creator_vault_authority" account.
func (inst *SellInstruction) SetCoinCreatorVaultAuthorityAccount(coinCreatorVaultAuthority ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[18] = ag_solanago.Meta(coinCreatorVaultAuthority)
	return inst
}

func (inst *SellInstruction) findFindCoinCreatorVaultAuthorityAddress(poolCoinCreator *ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: creator_vault
	seeds = append(seeds, []byte{byte(0x63), byte(0x72), byte(0x65), byte(0x61), byte(0x74), byte(0x6f), byte(0x72), byte(0x5f), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: pool.coin_creator
	seeds = append(seeds, poolCoinCreator.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCoinCreatorVaultAuthorityAddressWithBumpSeed calculates CoinCreatorVaultAuthority account address with given seeds and a known bump seed.
func (inst *SellInstruction) FindCoinCreatorVaultAuthorityAddressWithBumpSeed(poolCoinCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCoinCreatorVaultAuthorityAddress(poolCoinCreator, bumpSeed)
	return
}

func (inst *SellInstruction) MustFindCoinCreatorVaultAuthorityAddressWithBumpSeed(poolCoinCreator *ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAuthorityAddress(poolCoinCreator, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCoinCreatorVaultAuthorityAddress finds CoinCreatorVaultAuthority account address with given seeds.
func (inst *SellInstruction) FindCoinCreatorVaultAuthorityAddress(poolCoinCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCoinCreatorVaultAuthorityAddress(poolCoinCreator, 0)
	return
}

func (inst *SellInstruction) MustFindCoinCreatorVaultAuthorityAddress(poolCoinCreator *ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAuthorityAddress(poolCoinCreator, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCoinCreatorVaultAuthorityAccount gets the "coin_creator_vault_authority" account.
func (inst *SellInstruction) GetCoinCreatorVaultAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(18)
}

// SetFeeConfigAccount sets the "fee_config" account.
func (inst *SellInstruction) SetFeeConfigAccount(feeConfig ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[19] = ag_solanago.Meta(feeConfig)
	return inst
}

func (inst *SellInstruction) findFindFeeConfigAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: fee_config
	seeds = append(seeds, []byte{byte(0x66), byte(0x65), byte(0x65), byte(0x5f), byte(0x63), byte(0x6f), byte(0x6e), byte(0x66), byte(0x69), byte(0x67)})
	// const (raw): [12 20 222 252 130 94 198 118 148 37 8 24 187 101 64 101 244 41 141 49 86 213 113 180 212 248 9 12 24 233 168 99]
	seeds = append(seeds, []byte{byte(0xc), byte(0x14), byte(0xde), byte(0xfc), byte(0x82), byte(0x5e), byte(0xc6), byte(0x76), byte(0x94), byte(0x25), byte(0x8), byte(0x18), byte(0xbb), byte(0x65), byte(0x40), byte(0x65), byte(0xf4), byte(0x29), byte(0x8d), byte(0x31), byte(0x56), byte(0xd5), byte(0x71), byte(0xb4), byte(0xd4), byte(0xf8), byte(0x9), byte(0xc), byte(0x18), byte(0xe9), byte(0xa8), byte(0x63)})

	programID := Addresses["pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindFeeConfigAddressWithBumpSeed calculates FeeConfig account address with given seeds and a known bump seed.
func (inst *SellInstruction) FindFeeConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindFeeConfigAddress(bumpSeed)
	return
}

func (inst *SellInstruction) MustFindFeeConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindFeeConfigAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindFeeConfigAddress finds FeeConfig account address with given seeds.
func (inst *SellInstruction) FindFeeConfigAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindFeeConfigAddress(0)
	return
}

func (inst *SellInstruction) MustFindFeeConfigAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindFeeConfigAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetFeeConfigAccount gets the "fee_config" account.
func (inst *SellInstruction) GetFeeConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(19)
}

// SetFeeProgramAccount sets the "fee_program" account.
func (inst *SellInstruction) SetFeeProgramAccount(feeProgram ag_solanago.PublicKey) *SellInstruction {
	inst.AccountMetaSlice[20] = ag_solanago.Meta(feeProgram)
	return inst
}

// GetFeeProgramAccount gets the "fee_program" account.
func (inst *SellInstruction) GetFeeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(20)
}

func (inst SellInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Sell,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SellInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SellInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BaseAmountIn == nil {
			return errors.New("BaseAmountIn parameter is not set")
		}
		if inst.MinQuoteAmountOut == nil {
			return errors.New("MinQuoteAmountOut parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Pool is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.GlobalConfig is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BaseMint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.QuoteMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.UserQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.PoolBaseTokenAccount is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.PoolQuoteTokenAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.ProtocolFeeRecipient is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.ProtocolFeeRecipientTokenAccount is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.BaseTokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.QuoteTokenProgram is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[16] == nil {
			return errors.New("accounts.Program is not set")
		}
		if inst.AccountMetaSlice[17] == nil {
			return errors.New("accounts.CoinCreatorVaultAta is not set")
		}
		if inst.AccountMetaSlice[18] == nil {
			return errors.New("accounts.CoinCreatorVaultAuthority is not set")
		}
		if inst.AccountMetaSlice[19] == nil {
			return errors.New("accounts.FeeConfig is not set")
		}
		if inst.AccountMetaSlice[20] == nil {
			return errors.New("accounts.FeeProgram is not set")
		}
	}
	return nil
}

func (inst *SellInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Sell")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("        BaseAmountIn", *inst.BaseAmountIn))
						paramsBranch.Child(ag_format.Param("   MinQuoteAmountOut", *inst.MinQuoteAmountOut))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=21]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                         pool", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                         user", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                global_config", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                    base_mint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                   quote_mint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("             user_base_token_", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("            user_quote_token_", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("             pool_base_token_", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("            pool_quote_token_", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("       protocol_fee_recipient", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("protocol_fee_recipient_token_", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("           base_token_program", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("          quote_token_program", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("               system_program", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("     associated_token_program", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("              event_authority", inst.AccountMetaSlice.Get(15)))
						accountsBranch.Child(ag_format.Meta("                      program", inst.AccountMetaSlice.Get(16)))
						accountsBranch.Child(ag_format.Meta("       coin_creator_vault_ata", inst.AccountMetaSlice.Get(17)))
						accountsBranch.Child(ag_format.Meta(" coin_creator_vault_authority", inst.AccountMetaSlice.Get(18)))
						accountsBranch.Child(ag_format.Meta("                   fee_config", inst.AccountMetaSlice.Get(19)))
						accountsBranch.Child(ag_format.Meta("                  fee_program", inst.AccountMetaSlice.Get(20)))
					})
				})
		})
}

func (obj SellInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BaseAmountIn` param:
	err = encoder.Encode(obj.BaseAmountIn)
	if err != nil {
		return err
	}
	// Serialize `MinQuoteAmountOut` param:
	err = encoder.Encode(obj.MinQuoteAmountOut)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SellInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BaseAmountIn`:
	err = decoder.Decode(&obj.BaseAmountIn)
	if err != nil {
		return err
	}
	// Deserialize `MinQuoteAmountOut`:
	err = decoder.Decode(&obj.MinQuoteAmountOut)
	if err != nil {
		return err
	}
	return nil
}

// NewSellInstruction declares a new Sell instruction with the provided parameters and accounts.
func NewSellInstruction(
	// Parameters:
	base_amount_in uint64,
	min_quote_amount_out uint64,
	// Accounts:
	pool ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	globalConfig ag_solanago.PublicKey,
	baseMint ag_solanago.PublicKey,
	quoteMint ag_solanago.PublicKey,
	userBaseTokenAccount ag_solanago.PublicKey,
	userQuoteTokenAccount ag_solanago.PublicKey,
	poolBaseTokenAccount ag_solanago.PublicKey,
	poolQuoteTokenAccount ag_solanago.PublicKey,
	protocolFeeRecipient ag_solanago.PublicKey,
	protocolFeeRecipientTokenAccount ag_solanago.PublicKey,
	baseTokenProgram ag_solanago.PublicKey,
	quoteTokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey,
	coinCreatorVaultAta ag_solanago.PublicKey,
	coinCreatorVaultAuthority ag_solanago.PublicKey,
	feeConfig ag_solanago.PublicKey,
	feeProgram ag_solanago.PublicKey) *SellInstruction {
	return NewSellInstructionBuilder().
		SetBaseAmountIn(base_amount_in).
		SetMinQuoteAmountOut(min_quote_amount_out).
		SetPoolAccount(pool).
		SetUserAccount(user).
		SetGlobalConfigAccount(globalConfig).
		SetBaseMintAccount(baseMint).
		SetQuoteMintAccount(quoteMint).
		SetUserBaseTokenAccountAccount(userBaseTokenAccount).
		SetUserQuoteTokenAccountAccount(userQuoteTokenAccount).
		SetPoolBaseTokenAccountAccount(poolBaseTokenAccount).
		SetPoolQuoteTokenAccountAccount(poolQuoteTokenAccount).
		SetProtocolFeeRecipientAccount(protocolFeeRecipient).
		SetProtocolFeeRecipientTokenAccountAccount(protocolFeeRecipientTokenAccount).
		SetBaseTokenProgramAccount(baseTokenProgram).
		SetQuoteTokenProgramAccount(quoteTokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program).
		SetCoinCreatorVaultAtaAccount(coinCreatorVaultAta).
		SetCoinCreatorVaultAuthorityAccount(coinCreatorVaultAuthority).
		SetFeeConfigAccount(feeConfig).
		SetFeeProgramAccount(feeProgram)
}
