// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pumpamm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Transfer creator fees to pump creator vault
// If coin creator fees are currently below rent.minimum_balance(TokenAccount::LEN)
// The transfer will be skipped
type TransferCreatorFeesToPumpInstruction struct {

	// [0] = [] wsol_mint
	// ··········· Pump Canonical Pool are quoted in wSOL
	//
	// [1] = [] token_program
	//
	// [2] = [] system_program
	//
	// [3] = [] associated_token_program
	//
	// [4] = [] coin_creator
	//
	// [5] = [WRITE] coin_creator_vault_authority
	//
	// [6] = [WRITE] coin_creator_vault_ata
	//
	// [7] = [WRITE] pump_creator_vault
	//
	// [8] = [] event_authority
	//
	// [9] = [] program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferCreatorFeesToPumpInstructionBuilder creates a new `TransferCreatorFeesToPumpInstruction` instruction builder.
func NewTransferCreatorFeesToPumpInstructionBuilder() *TransferCreatorFeesToPumpInstruction {
	nd := &TransferCreatorFeesToPumpInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	nd.AccountMetaSlice[2] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	nd.AccountMetaSlice[3] = ag_solanago.Meta(Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"])
	return nd
}

// SetWsolMintAccount sets the "wsol_mint" account.
// Pump Canonical Pool are quoted in wSOL
func (inst *TransferCreatorFeesToPumpInstruction) SetWsolMintAccount(wsolMint ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(wsolMint)
	return inst
}

// GetWsolMintAccount gets the "wsol_mint" account.
// Pump Canonical Pool are quoted in wSOL
func (inst *TransferCreatorFeesToPumpInstruction) GetWsolMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAssociatedTokenProgramAccount sets the "associated_token_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associated_token_program" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetCoinCreatorAccount sets the "coin_creator" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetCoinCreatorAccount(coinCreator ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(coinCreator)
	return inst
}

// GetCoinCreatorAccount gets the "coin_creator" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetCoinCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetCoinCreatorVaultAuthorityAccount sets the "coin_creator_vault_authority" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetCoinCreatorVaultAuthorityAccount(coinCreatorVaultAuthority ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(coinCreatorVaultAuthority).WRITE()
	return inst
}

func (inst *TransferCreatorFeesToPumpInstruction) findFindCoinCreatorVaultAuthorityAddress(coinCreator ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: creator_vault
	seeds = append(seeds, []byte{byte(0x63), byte(0x72), byte(0x65), byte(0x61), byte(0x74), byte(0x6f), byte(0x72), byte(0x5f), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: coin_creator
	seeds = append(seeds, coinCreator.Bytes())

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindCoinCreatorVaultAuthorityAddressWithBumpSeed calculates CoinCreatorVaultAuthority account address with given seeds and a known bump seed.
func (inst *TransferCreatorFeesToPumpInstruction) FindCoinCreatorVaultAuthorityAddressWithBumpSeed(coinCreator ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCoinCreatorVaultAuthorityAddress(coinCreator, bumpSeed)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindCoinCreatorVaultAuthorityAddressWithBumpSeed(coinCreator ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAuthorityAddress(coinCreator, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCoinCreatorVaultAuthorityAddress finds CoinCreatorVaultAuthority account address with given seeds.
func (inst *TransferCreatorFeesToPumpInstruction) FindCoinCreatorVaultAuthorityAddress(coinCreator ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCoinCreatorVaultAuthorityAddress(coinCreator, 0)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindCoinCreatorVaultAuthorityAddress(coinCreator ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAuthorityAddress(coinCreator, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCoinCreatorVaultAuthorityAccount gets the "coin_creator_vault_authority" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetCoinCreatorVaultAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetCoinCreatorVaultAtaAccount sets the "coin_creator_vault_ata" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetCoinCreatorVaultAtaAccount(coinCreatorVaultAta ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(coinCreatorVaultAta).WRITE()
	return inst
}

func (inst *TransferCreatorFeesToPumpInstruction) findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, wsolMint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// path: coin_creator_vault_authority
	seeds = append(seeds, coinCreatorVaultAuthority.Bytes())
	// path: token_program
	seeds = append(seeds, tokenProgram.Bytes())
	// path: wsol_mint
	seeds = append(seeds, wsolMint.Bytes())

	programID := Addresses["ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindCoinCreatorVaultAtaAddressWithBumpSeed calculates CoinCreatorVaultAta account address with given seeds and a known bump seed.
func (inst *TransferCreatorFeesToPumpInstruction) FindCoinCreatorVaultAtaAddressWithBumpSeed(coinCreatorVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, wsolMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, tokenProgram, wsolMint, bumpSeed)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindCoinCreatorVaultAtaAddressWithBumpSeed(coinCreatorVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, wsolMint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, tokenProgram, wsolMint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindCoinCreatorVaultAtaAddress finds CoinCreatorVaultAta account address with given seeds.
func (inst *TransferCreatorFeesToPumpInstruction) FindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, wsolMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, tokenProgram, wsolMint, 0)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority ag_solanago.PublicKey, tokenProgram ag_solanago.PublicKey, wsolMint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindCoinCreatorVaultAtaAddress(coinCreatorVaultAuthority, tokenProgram, wsolMint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetCoinCreatorVaultAtaAccount gets the "coin_creator_vault_ata" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetCoinCreatorVaultAtaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetPumpCreatorVaultAccount sets the "pump_creator_vault" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetPumpCreatorVaultAccount(pumpCreatorVault ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(pumpCreatorVault).WRITE()
	return inst
}

func (inst *TransferCreatorFeesToPumpInstruction) findFindPumpCreatorVaultAddress(coinCreator ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: creator-vault
	seeds = append(seeds, []byte{byte(0x63), byte(0x72), byte(0x65), byte(0x61), byte(0x74), byte(0x6f), byte(0x72), byte(0x2d), byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: coin_creator
	seeds = append(seeds, coinCreator.Bytes())

	programID := Addresses["6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"]

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, programID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, programID)
	}
	return
}

// FindPumpCreatorVaultAddressWithBumpSeed calculates PumpCreatorVault account address with given seeds and a known bump seed.
func (inst *TransferCreatorFeesToPumpInstruction) FindPumpCreatorVaultAddressWithBumpSeed(coinCreator ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindPumpCreatorVaultAddress(coinCreator, bumpSeed)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindPumpCreatorVaultAddressWithBumpSeed(coinCreator ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindPumpCreatorVaultAddress(coinCreator, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindPumpCreatorVaultAddress finds PumpCreatorVault account address with given seeds.
func (inst *TransferCreatorFeesToPumpInstruction) FindPumpCreatorVaultAddress(coinCreator ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindPumpCreatorVaultAddress(coinCreator, 0)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindPumpCreatorVaultAddress(coinCreator ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindPumpCreatorVaultAddress(coinCreator, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetPumpCreatorVaultAccount gets the "pump_creator_vault" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetPumpCreatorVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEventAuthorityAccount sets the "event_authority" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetEventAuthorityAccount(eventAuthority ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(eventAuthority)
	return inst
}

func (inst *TransferCreatorFeesToPumpInstruction) findFindEventAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: __event_authority
	seeds = append(seeds, []byte{byte(0x5f), byte(0x5f), byte(0x65), byte(0x76), byte(0x65), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindEventAuthorityAddressWithBumpSeed calculates EventAuthority account address with given seeds and a known bump seed.
func (inst *TransferCreatorFeesToPumpInstruction) FindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindEventAuthorityAddress(bumpSeed)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindEventAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindEventAuthorityAddress finds EventAuthority account address with given seeds.
func (inst *TransferCreatorFeesToPumpInstruction) FindEventAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindEventAuthorityAddress(0)
	return
}

func (inst *TransferCreatorFeesToPumpInstruction) MustFindEventAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindEventAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetEventAuthorityAccount gets the "event_authority" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetEventAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetProgramAccount sets the "program" account.
func (inst *TransferCreatorFeesToPumpInstruction) SetProgramAccount(program ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(program)
	return inst
}

// GetProgramAccount gets the "program" account.
func (inst *TransferCreatorFeesToPumpInstruction) GetProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst TransferCreatorFeesToPumpInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferCreatorFeesToPump,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferCreatorFeesToPumpInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferCreatorFeesToPumpInstruction) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.WsolMint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.CoinCreator is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.CoinCreatorVaultAuthority is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.CoinCreatorVaultAta is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.PumpCreatorVault is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.EventAuthority is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Program is not set")
		}
	}
	return nil
}

func (inst *TransferCreatorFeesToPumpInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferCreatorFeesToPump")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                   wsol_mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("               token_program", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("              system_program", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("    associated_token_program", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                coin_creator", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("coin_creator_vault_authority", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("      coin_creator_vault_ata", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          pump_creator_vault", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("             event_authority", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                     program", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj TransferCreatorFeesToPumpInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *TransferCreatorFeesToPumpInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewTransferCreatorFeesToPumpInstruction declares a new TransferCreatorFeesToPump instruction with the provided parameters and accounts.
func NewTransferCreatorFeesToPumpInstruction(
	// Accounts:
	wsolMint ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	coinCreator ag_solanago.PublicKey,
	coinCreatorVaultAuthority ag_solanago.PublicKey,
	coinCreatorVaultAta ag_solanago.PublicKey,
	pumpCreatorVault ag_solanago.PublicKey,
	eventAuthority ag_solanago.PublicKey,
	program ag_solanago.PublicKey) *TransferCreatorFeesToPumpInstruction {
	return NewTransferCreatorFeesToPumpInstructionBuilder().
		SetWsolMintAccount(wsolMint).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetCoinCreatorAccount(coinCreator).
		SetCoinCreatorVaultAuthorityAccount(coinCreatorVaultAuthority).
		SetCoinCreatorVaultAtaAccount(coinCreatorVaultAta).
		SetPumpCreatorVaultAccount(pumpCreatorVault).
		SetEventAuthorityAccount(eventAuthority).
		SetProgramAccount(program)
}
